// Direct teacher instruction: a "what's new" changelog, shown as a real
// page-turning book (same BookPanel the Joke Book/Pet Book already use),
// one change per page, auto-opening the first time a student logs in
// after something new that affects them has shipped. This file is the
// one place that list lives — student-facing only (a Build Mode tooling
// fix, for instance, never belongs here), plain language, newest first.
// Maintenance convention: add a new entry here whenever a change actually
// visible/usable by a student ships, using today's date and a short id.
export interface ChangelogEntry {
  id: string; // stable, unique, sorts newest-first alongside `date`
  date: string; // YYYY-MM-DD
  icon: string;
  title: string;
  body: string;
}

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
  {
    id: '2026-10-07-gus-audit-fixes',
    date: '2026-10-07',
    icon: '🔧',
    title: 'Sharper grammar checks',
    body: "Gus now checks for a comma before and, but or so when they join two whole ideas, and catches extra commas and extra capital letters. The biggest cat takes \"the\". On Guided and Challenge help, the gadgets light up a mistake for you to fix instead of fixing it for you. The Slot Machine is now the Word Shuffler, and the Calm button is back on the top bar.",
  },
  {
    id: '2026-10-07-gus-blueprints',
    date: '2026-10-07',
    icon: '📐',
    title: 'Orders, Blueprints and Remix',
    body: "Open Jobs on Gus's Workboard. Gus's Order shows a scene in pictures: build any sentence that makes it. Blueprints deliver a whole story, news report or joke as linked machines for you to fill in. Tap Remix under a sentence to make it longer, shorter or sillier.",
  },
  {
    id: '2026-10-07-gus-slots',
    date: '2026-10-07',
    icon: '🎰',
    title: 'Slot Machine and Spare Parts Bin',
    body: "Snap on the Slot Machine and tap Spin for brand new words in the same sentence shape. Lock a word you love in its menu. Try the Mystery Crate, the Echo Megaphone, the Time Warp Toaster and the Pronoun Cannon. Drag extra parts into the Spare Parts Bin to save them for later. Turn on Read words out loud in the Menu to hear every word you pick.",
  },
  {
    id: '2026-10-07-gus-questions',
    date: '2026-10-07',
    icon: '🏗️',
    title: 'Questions, speech bubbles and more',
    body: "The Question Crane turns your sentence into a question: Does the cat jump? Add a Question Mark on the end. The Speech Bubble Blower adds quotation marks and a speaker. The Tag Gun makes the dog's bone, the Size-Up Inflator makes bigger and biggest, and the Because Seesaw joins a reason to a result.",
  },
  {
    id: '2026-10-07-gus-checklist-review',
    date: '2026-10-07',
    icon: '✅',
    title: 'Snap parts on top and underneath',
    body: "Snap the Capital Letter Press under the first word, and punctuation on top of the last word. Gus's Checklist now stays open next to your machine. Pull the Start Lever and watch it check off everything you got right. Then read Gus's review: stars for your sentence, ideas to make it bigger, and a quick question about it for a bonus gear.",
  },
  {
    id: '2026-10-07-gus-combos',
    date: '2026-10-07',
    icon: '💥',
    title: 'Combos, names and weird plurals',
    body: "Five more machine parts: the Name Stamp (Mia, Vermont), the Plural Crusher (mouse to mice!), the Irregular Past Press (not goed, went!), the Comma List Train and the Pronoun Turnstile (he or him?). Put certain parts together on one machine for a COMBO and bonus gears. Can you find all seven? Spin words with the new reel in any word menu, and watch sound words pop on the TV.",
  },
  {
    id: '2026-10-07-gus-gadgets',
    date: '2026-10-07',
    icon: '🔧',
    title: '14 new machine parts',
    body: "Turn the Clock to Past or Future and watch the action words change. New parts: the Time Tunnel (long ago, next week), the Mood Meter (calm or BIG feelings), the Confetti Trapdoor, the Slingshot, the How-Dial that makes the marble creep or zoom, the Merge Funnel, the Comma Drawbridge, and Helper Gadgets that sniff out a and an, sort describing words and zap repeated nouns into he, she, it or they. Snap every part in the right order or the machine will not run!",
  },
  {
    id: '2026-10-07-gus-fun-parts',
    date: '2026-10-07',
    icon: '📯',
    title: 'Fun parts that do grammar',
    body: "Gus's parts menu is on the left now, and you can fold each group. Every fun part does a job: the Big Horn honks an exclamation point, the Spring Mat bounces in a describing word, the Bell rings a period, and the Duplicator copies a noun so there are more than one. Parts snap into place, gears whir, steam puffs from the pipes, and every part pops its sound. Try Surprise me in a word menu and watch your Silly-o-meter!",
  },
  {
    id: '2026-10-07-gus-time-words',
    date: '2026-10-07',
    icon: '🔗',
    title: 'Time words for paragraphs',
    body: 'When you hook sentences together with a Paragraph Link, tap "+ time word" under a sentence to add First, Then, Next or Finally. Your paragraph reads in order, and you earn a bonus gear. Your stickers now show on the Workboard too.',
  },
  {
    id: '2026-10-07-gus-jobs',
    date: '2026-10-07',
    icon: '🧰',
    title: "Gus's Jobs",
    body: "Tap Jobs on Gus's Workboard. A Mixed-up Delivery brings word machines in the wrong order for you to fix. The Punctuation Inspector brings a machine with one capital letter or punctuation mistake to find. Finish a job for gears and a sticker. You can also tap Hear it under any sentence, and Undo any change.",
  },
  {
    id: '2026-10-07-gus-contraption',
    date: '2026-10-07',
    icon: '⚙️',
    title: 'Build the whole contraption',
    body: "Every word machine is now shaped like its grammar symbol: the noun is a big red triangle and the verb is a green wheel. Start from a blank space and build the whole machine yourself: Start Lever, words, Capital Letter Press, punctuation and the Pixel TV. Add a Clock to set past, present or future, spring mats and pulleys for the marble to roll through, and a Paragraph Link to hook sentences into a paragraph. Type any real word and Gus checks his dictionary.",
  },
  {
    id: '2026-10-07-gus-workboard',
    date: '2026-10-07',
    icon: '🏭',
    title: "Gus's new Workboard",
    body: "Grammar Gus now has a big factory floor. Pull machines out of the Parts drawer: every word is its own machine. Tap a machine to pick its word, or start typing and Gus guesses the word for you. Plug in the Big Letter Press, a Stop Stamp and the Pixel TV, then pull the lever and watch your sentence on the TV. Pinch to zoom, and build more machines to make a story.",
  },
  {
    id: '2026-10-07-gus-packs',
    date: '2026-10-07',
    icon: '🚀',
    title: 'Space and Ocean words for Gus',
    body: "Gus's Parts Bin has new Space and Ocean words: astronauts, aliens, robots, rockets, sharks, octopuses, whales, submarines and more. Try \"The shiny robot zoomed weirdly.\" and watch it on the pixel screen.",
  },
  {
    id: '2026-10-07-gus-garage',
    date: '2026-10-07',
    icon: '🎨',
    title: "Paint Gus's machine",
    body: "Tap the paint palette in Gus's machine to open the Garage. Pick Brass Works, Copper and Teal, Candy Factory, Night Shift or Calm Flat. Your machine remembers your pick.",
  },
  {
    id: '2026-10-07-gus-remix',
    date: '2026-10-07',
    icon: '🎛️',
    title: 'Remix and Label It',
    body: "Tap Remix on Gus's machine to roll a new word, make your sentence sillier, longer or shorter, swap in he, she or it, or zap the time. Then try Label It: put the WHO, WHAT THEY DID and WHERE brackets on your sentence, or match the symbols to the words.",
  },
  {
    id: '2026-10-07-gus-orders',
    date: '2026-10-07',
    icon: '🎯',
    title: "Fill Gus's Orders",
    body: "Tap Orders in Gus's machine. Gus shows you a scene he wants, like a big dog jumping over a van. Build any sentence that makes that scene to win gears and a sticker. Stuck? Tap Hint.",
  },
  {
    id: '2026-10-07-gus-blueprints',
    date: '2026-10-07',
    icon: '📜',
    title: 'Blueprints: jokes, stories and riddles',
    body: "Tap Blueprints in Gus's machine to build a whole knock-knock joke, a silly story, a news report or a riddle. Gus sets up a machine for every line. You fill in the symbols with silly words, then watch it play as one movie.",
  },
  {
    id: '2026-10-07-gus-movies',
    date: '2026-10-07',
    icon: '🎬',
    title: "Gus's movies got way more action",
    body: 'Every animal, car and thing now has its own pixel picture, and every action word really happens. Birds fly, frogs hop, snakes slither, cats sing music notes, things melt into puddles and kids hide behind bushes. Try loudly, tenderly or messily and watch what changes.',
  },
  {
    id: '2026-10-07-gus-stories',
    date: '2026-10-07',
    icon: '🎞️',
    title: 'Build a whole story with Gus',
    body: 'After your sentence plays, tap Seal it. It drops into the film strip and you get a fresh machine. Seal up to 4 sentences, then tap Play All to watch your story as one movie. Bring a character back with "the" and Gus gives you extra stars.',
  },
  {
    id: '2026-10-07-arcade-picker',
    date: '2026-10-07',
    icon: '🕹️',
    title: 'Pick your game at the arcade',
    body: 'Every game now sits in its own arcade cabinet. Swipe, or tap the big gold arrows, to slide through them, then tap Play.',
  },
  {
    id: '2026-10-07-gus-drag',
    date: '2026-10-07',
    icon: '🏭',
    title: "Drag parts into Gus's machine",
    body: "Every word is now a real machine part: a boiler, an engine, a gauge and more. Drag a part onto the machine and it snaps in. Drag it again to move it, or drag it off to recycle it. Watch the lights, and pull START!",
  },
  {
    id: '2026-10-07-grammar-gus',
    date: '2026-10-07',
    icon: '🧪',
    title: "Meet Grammar Gus's Contraption!",
    body: "Grammar Gus built a sentence machine, and it only runs on correct sentences. Tap the Grammar Gus card on your computer. Put words into WHO, WHAT THEY DID and HOW, pull START, and a great sentence plays as a little pixel movie. Gus is very fancy about grammar, so if the machine leaks steam, he will tell you what to fix.",
  },
  {
    id: '2026-10-06-pets-overhaul',
    date: '2026-10-06',
    icon: '🚧',
    title: 'Pets are getting an overhaul!',
    body: 'The whole pet system is being rebuilt to be bigger and better than ever. While that happens, the Pet Shelter is closed and pets are paused. If you had a pet, it has gone back to the Shelter and the full amount it was worth is now in your bank. Check your bank register! Stay tuned.',
  },
  {
    id: '2026-10-06-pet-training',
    date: '2026-10-06',
    icon: '🎪',
    title: 'Train your pet!',
    body: 'Tap your pet at home or tap Train on its card. Say the trick, watch your pet do it, and give it a treat 3 times to teach it. Your pet now lives inside your rooms too, and it learns from your games: every 10 right answers trains it a little more. Show off tricks in Town from the Companion menu!',
  },
  {
    id: '2026-10-06-streak-ten',
    date: '2026-10-06',
    icon: '🔥',
    title: 'Streaks just got easier',
    body: 'Now you only need 10 right answers a day to keep your streak going. Watch your fire meter fill up!',
  },
  {
    id: '2026-10-04-say-it',
    date: '2026-10-04',
    icon: '🎤',
    title: 'Say your answer out loud',
    body: 'Some quiz questions now let you answer with your voice! Tap the big microphone and say it. If it heard you wrong, you can try again or tap "That\'s what I said!"',
  },
  {
    id: '2026-10-04-bawk-reminders',
    date: '2026-10-04',
    icon: '🐓',
    title: 'Bawk has jokes for you',
    body: 'If you play in Town Square for a while with work still waiting, Bawk the rooster pops in with a silly joke and takes you right to your next activity. You need to cockadoodle DO it!',
  },
  {
    id: '2026-10-04-daily-streak',
    date: '2026-10-04',
    icon: '🔥',
    title: 'Daily Streaks and treasure chests!',
    body: 'Answer 20 questions right each day to keep your streak going. Watch the fire meter at the top of your screen. Every day you save your streak, you open treasure chests full of money! Streak Freezes keep your streak safe on days you miss. You start with one free.',
  },
  {
    id: '2026-10-04-game-dashboard',
    date: '2026-10-04',
    icon: '🕹️',
    title: 'The Game Dashboard is here',
    body: 'Open the new Games app on your computer to see every game in one place and pick the one you want. Some assignments let you choose your game too! In Town Square you can now zoom in close behind your character (pinch, scroll, or tap + and -). Double tap a Neighbor to open their menu.',
  },
  {
    id: '2026-10-04-play-with-neighbors',
    date: '2026-10-04',
    icon: '🎮',
    title: 'Play games with any Neighbor',
    body: 'Tap a Neighbor and pick Play a game! Choose Space Bowling, Slime Chess, Bakery Match or Castle Defense and play with them. Their About card remembers every game you played together. And watch out when you drive: bump a Neighbor and they hop out of the way!',
  },
  {
    id: '2026-10-04-dollar-answers',
    date: '2026-10-04',
    icon: '💵',
    title: '$1 for every right answer in games',
    body: 'Every right answer in Space Bowling, Slime Chess, Bakery Match, Castle Defense and the Gas Pump now earns you $1. Answer 20 right and earn $20! Space Bowling and Castle Defense also have your own personal best games list now.',
  },
  {
    id: '2026-10-04-bowling-neighbors',
    date: '2026-10-04',
    icon: '🎳',
    title: 'Play games with your Neighbors',
    body: 'In Space Bowling and Slime Chess you now play against a Neighbor instead of the computer. Talk to them later and they might remember your game! The bowling pins also face you now, tumble down one by one, and the UFO really beams them away. Space Bowling has a sparkly new pink galaxy behind it too.',
  },
  {
    id: '2026-10-04-car-dash',
    date: '2026-10-04',
    icon: '🚗',
    title: 'Cars have a dashboard',
    body: 'Hop in a car and look at the top of the screen! There is a gas dial, a speedometer, a radio that shows your song, a volume knob you can turn, and a trip counter. Tap the radio to pick a new song.',
  },
  {
    id: '2026-10-04-flat-world',
    date: '2026-10-04',
    icon: '🌍',
    title: 'A clean, flat horizon',
    body: 'The big strange shapes far away are gone. Now the ground goes all the way to the sky, flat and clear. Solid things in town are really solid too, so you cannot walk or drive through them.',
  },
  {
    id: '2026-10-04-clear-skies',
    date: '2026-10-04',
    icon: '🌤️',
    title: 'Clear views and changing skies',
    body: 'No more fog! You can see all the way across town now. The sky also changes every few minutes while you play, so keep looking up.',
  },
  {
    id: '2026-10-04-talk-scene',
    date: '2026-10-04',
    icon: '💬',
    title: 'Talking with Neighbors got a big new look',
    body: 'Now you and the Neighbor both stand on the screen and your mouths move when you talk! The chat writes itself in the little window at the top. You can tell any Neighbor or townsperson about your feelings too.',
  },
  {
    id: '2026-10-04-space-bowling',
    date: '2026-10-04',
    icon: '🪐',
    title: 'New game: Space Bowling!',
    body: 'Roll silly planets at alien cat pins! Answer questions before your turn, tap a lane number to roll, and hit the glowing asteroids for power-ups: the UFO beams up pins, the Strike Shuttle gets a strike, and the Meteor Shower messes up the next player. Play the computer or friends. Get 500 answers right to earn the Space Alien costume!',
  },
  {
    id: '2026-10-04-neighbors-new-look',
    date: '2026-10-04',
    icon: '🏘️',
    title: 'Your Neighbors got a new look',
    body: 'Scout, Penny, Pip, Wren and the townspeople are now cute animals in fun outfits! Tap a Neighbor to pick what to talk about, like a joke or your feelings. Tap About to see their character card with fun facts about them.',
  },
  {
    id: '2026-10-04-seamstress-open',
    date: '2026-10-04',
    icon: '🧵',
    title: 'The Seamstress is open!',
    body: 'Make your very own character! Pick a dog, cat, frog or capybara (your first one is free), color it any way you like, and dress it up. Bawk the rooster will show you how, step by step. Tap Style in the Menu, or walk into the Seamstress.',
  },
  {
    id: '2026-10-04-spin-in-town',
    date: '2026-10-04',
    icon: '🎡',
    title: 'Daily Spin and Piggy Bank in Town Square',
    body: 'Your Daily Spin now pops up as soon as you get to Town Square each day, so you can spin right away. Your Piggy Bank is in the Menu too: tap Menu, then the pig.',
  },
  {
    id: '2026-10-01-chess-leaderboard',
    date: '2026-10-01',
    icon: '⭐',
    title: 'Slime Chess: earn XP and beat your best',
    body: 'Every piece you capture from the computer earns XP, just like real chess points: Pawn 1, Knight 3, Bishop 3, Rook 5, Queen 9. Your top 5 games show on My Chess Leaderboard on the chess start screen. Can you beat your own record?',
  },
  {
    id: '2026-10-01-question-tools',
    date: '2026-10-01',
    icon: '🧰',
    title: 'Question tools work now',
    body: 'Tap the toolbox on any question screen. Calculator does math for you, Scratchpad lets you draw and work it out, Text Size makes the words bigger, and Highlight lets you tap words to mark them. You can drag the Calculator and Scratchpad out of the way.',
  },
  {
    id: '2026-10-01-slime-chess-turns',
    date: '2026-10-01',
    icon: '♟️',
    title: 'Slime Chess: clearer turns and warnings',
    body: 'After the computer moves, you get 3 seconds to see its move before your question. Playing with a friend? A card shows whose turn it is, and the question says whose it is too. A yellow ! bubble now shows every square where your piece could be captured. Leaving a game asks first, so you never quit by accident.',
  },
  {
    id: '2026-10-01-slime-chess-calm',
    date: '2026-10-01',
    icon: '🫧',
    title: 'Slime Chess: Less motion, and a computer that thinks',
    body: 'Open the gear in Slime Chess and tap Less motion to stop the wobbling and bouncing. The computer now takes a few seconds to think before it moves. The board only shows three colors now: can move, can capture, and risky.',
  },
  {
    id: '2026-10-01-slime-chess-questions',
    date: '2026-10-01',
    icon: '⚙️',
    title: 'Slime Chess: a question each turn, and a new settings button',
    body: 'Before each of your turns in Slime Chess, answer one question, then make your move. Hint, Undo, Danger, Sound and New game are now inside the gear button at the top. Tap it to open a round menu. The pieces you capture show up right under Your turn.',
  },
  {
    id: '2026-10-01-slime-chess',
    date: '2026-10-01',
    icon: '♟️',
    title: 'New game: Slime Chess',
    body: 'Find the chess set in Town Square and play real chess with squishy jelly pieces! Play the computer or a friend. Tap a piece to see every square it can go to. Stuck? Tap Hint for an idea. If a move does not work, a bubble tells you why.',
  },
  {
    id: '2026-10-01-neighbor-chat-menu',
    date: '2026-10-01',
    icon: '😄',
    title: 'Chat with Neighbors: jokes or feelings',
    body: 'When you talk to a Neighbor you have already met, you can pick what to chat about. Tap Tell me a joke for a new joke for your Joke Book, or tap Talk about my feelings to tell them how you feel. You can leave any time.',
  },
  {
    id: '2026-10-01-castle-map',
    date: '2026-10-01',
    icon: '🗺️',
    title: 'Castle Defense has a brand new map',
    body: 'The whole screen is the battlefield now: a winding sand road through a forest, a pond, and a real castle at the end. Glowing spots show where you can build or upgrade. Attackers walk the road and your towers fire right at them.',
  },
  {
    id: '2026-10-01-neighbor-checkin-look',
    date: '2026-10-01',
    icon: '💬',
    title: 'Neighbors check in with a new look',
    body: 'When a Neighbor checks in on you, they are right there in the corner, moving and talking. What they say is in the middle, your answer buttons are right under it, and the whole conversation is saved on the side so you can read it again.',
  },
  {
    id: '2026-10-01-sel-checkin',
    date: '2026-10-01',
    icon: '🌈',
    title: 'A quick check-in when you log in',
    body: 'When you tap your avatar, you will be asked how you are feeling. Pick the zone and word that is true for you right now. Every zone is okay. If you pick anything other than Green, you will see some tools that might help, and you can leave a note for your teacher too.',
  },
  {
    id: '2026-09-30-castle-defense',
    date: '2026-09-30',
    icon: '🏰',
    title: 'New game: Castle Defense',
    body: 'Walk up to the Castle in Town Square to play! Answer questions to earn gems, build and upgrade towers, and watch them fire at attackers in real battles across 5 waves. Finish the whole game to earn money and a bonus spin.',
  },
  {
    id: '2026-09-30-break-button-removed',
    date: '2026-09-30',
    icon: '🌿',
    title: 'The break button is gone',
    body: 'The "I need a break" button is no longer in the Take a Moment screen. Breathing, checking on your pet, and asking for your teacher are all still there.',
  },
  {
    id: '2026-09-30-playground-retired',
    date: '2026-09-30',
    icon: '🎮',
    title: 'The Playground is now the games',
    body: 'The old Playground page is gone. Instead, you can play games like Bakery Match and the Gas Pump anytime you want, and answering questions there still counts toward your assignments.',
  },
  {
    id: '2026-09-29-bakery-match-goal',
    date: '2026-09-29',
    icon: '🎯',
    title: 'Bakery Match has a new money goal',
    body: 'Tap the goal button at the top of Bakery Match to see how many questions you need to answer to earn a big cash prize. Answer 100 questions and get $100. Then the goal grows and so does the prize! You can also see how much you have earned while playing, right next to the goal.',
  },
  {
    id: '2026-09-29-bakery-match-cash',
    date: '2026-09-29',
    icon: '🪙',
    title: 'Bakery Match now pays real money',
    body: 'Every question you answer correctly in Bakery Match earns you $0.50, right into your Piggy Bank. When you finish a whole game, you get a coin celebration showing how much you earned, plus a bonus spin on the Daily Spin wheel.',
  },
  {
    id: '2026-09-29-roads-walkable-again',
    date: '2026-09-29',
    icon: '🛣️',
    title: 'Roads and paths work again',
    body: 'You can walk and drive on roads, paths, floors, and train tracks again, and nobody gets stuck at the edge of town anymore. The townspeople are free to wander too.',
  },
  {
    id: '2026-09-25-bakery-wheel-sparkles',
    date: '2026-09-25',
    icon: '🎡',
    title: 'Bakery Treat Wheel got bigger and sparklier',
    body: 'The Bakery Match prize wheel is bigger now and shows a real picture of each treat, so you can actually see what you might win. When your spin lands, your prize pops up with sparkles and a fun little sound.',
  },
  {
    id: '2026-09-25-bakery-match-visual-polish',
    date: '2026-09-25',
    icon: '🍩',
    title: 'Bakery Match looks more like a real bakery now',
    body: 'The Bakery Match main menu and game board got a fresh coat of paint, a bigger playful title, and more floating treats around the edges, closer to how it was designed to look.',
  },
  {
    id: '2026-09-25-mixed-up-answer-order',
    date: '2026-09-25',
    icon: '🔀',
    title: 'Answer choices are mixed up now',
    body: 'In quizzes, the gas pump, Bakery Match, and platformer games, the right answer used to often show up in the same spot. Now the order of answer choices gets mixed up every time, so read carefully!',
  },
  {
    id: '2026-09-25-bakery-match-game-screen',
    date: '2026-09-25',
    icon: '🥐',
    title: 'Bakery Match got a whole new look and new rules',
    body: 'Bakery Match no longer looks like a computer webpage, it now opens with a real game start screen. Tap Play New Game to start, or View Leaderboard to see your past scores (only you can see them). You can now drag a treat onto the one next to it to swap, or still tap two treats like before. A game is 3 rounds of 3 moves each, and after every round you answer 3 questions correctly before the next round starts. Matching treats earns you XP instead of coins, and after your 3rd round you get one wheel spin for a treat prize.',
  },
  {
    id: '2026-09-25-question-screen-redesign',
    date: '2026-09-25',
    icon: '❓',
    title: 'New look for gas station and bakery questions',
    body: 'The questions you answer to fill up your car with gas, and the bonus question between Bakery Match rounds, both got a fresh new look. If you pick a wrong answer it will not count against you, just try again. Tap Listen to hear the question and every answer choice read out loud. There is also a new toolbox button in the corner, more tools are coming soon there.',
  },
  {
    id: '2026-09-25-real-icons-pass-1',
    date: '2026-09-25',
    icon: '🖼️',
    title: 'Some emoji became real pictures',
    body: 'Around Town Square, the Marketplace, your task list, and the Tools menu, some emoji buttons now show real little pictures instead, like the X to close a window, the checkmark when you finish something, and the lock on things you can’t afford yet. More of these will keep changing over to real pictures over time.',
  },
  {
    id: '2026-09-25-book-paper-reskin',
    date: '2026-09-25',
    icon: '📖',
    title: 'Books got a new paper look',
    body: 'The Joke Book, Pet Book, and this What’s New book now look like real paper, with a ribbon banner for the title and paper page-turn buttons.',
  },
  {
    id: '2026-09-25-solid-objects-full-footprint',
    date: '2026-09-25',
    icon: '🧱',
    title: 'Solid objects now block your whole path',
    body: 'Long or wide objects your teacher builds with, like a wide building or a long wall, used to let you sneak through part of them even though they looked solid. Now the whole shape you see is the shape that actually blocks you, for walking, for Neighbors and other characters, and for cars too.',
  },
  {
    id: '2026-09-25-lot-expand',
    date: '2026-09-25',
    icon: '📐',
    title: 'Town Square can get bigger',
    body: 'Your teacher can now push the walls of Town Square outward to make more room to walk, drive, and build in. Open the overhead Map to see the walkable area change shape as your teacher grows it in different directions.',
  },
  {
    id: '2026-09-25-question-screens-bigger',
    date: '2026-09-25',
    icon: '⛽',
    title: 'Bigger, friendlier question screens',
    body: 'The gas pump and Bakery Match question screens are bigger now, with a progress bar so you can see how close you are, and a listen button so you can hear the question read out loud. Getting gas: missing a question never sets you back, it just does not count that one. There is now an exit button too, it will just let you know you will need to get out of the car if you use it.',
  },
  {
    id: '2026-09-25-planes-drone-shipped',
    date: '2026-09-25',
    icon: '✈️',
    title: 'You can fly a plane or a drone now',
    body: 'Find a plane or a drone and click it to hop in. Press Takeoff to lift off, then use the buttons to turn and change your altitude. When you are ready to come back down, press Land. Click the plane or drone again to get out once you have landed.',
  },
  {
    id: '2026-09-25-lm-matrix-web-writing',
    date: '2026-09-25',
    icon: '📝',
    title: 'Word Matrix, Word Web, and Writing Scaffolds',
    body: 'Morphemes now has a Word Matrix (pick a root and see which prefixes and suffixes make real words) and a Reverse Morphology prompt card, plus little connector lines when word parts join. There is also a new Writing Scaffolds category with writing frames and sentence starters to help you get your ideas down.',
  },
  {
    id: '2026-09-25-bakery-match3-rounds',
    date: '2026-09-25',
    icon: '🎂',
    title: 'Bakery Match now has rounds, and a Cake Character to earn',
    body: 'Bakery Match now plays in rounds, each one a little longer than the last. Finish a round and answer a quick question to move on, and pick how you want your questions: a dice for a random mix, or a dropdown to choose one question set. Answer 100 questions total in Bakery Match and you unlock a Cake Character you can walk around Town Square as!',
  },
  {
    id: '2026-09-25-bakery-match3',
    date: '2026-09-25',
    icon: '🥐',
    title: 'The Bakery is open in Town Square!',
    body: 'Walk up to the new Bakery to play a match-3 treat game. Answer a quick question every so often to keep baking, and when you are done, spin the treat wheel! You can eat what you win or give it to one of your pets to fill up their food bar.',
  },
  {
    id: '2026-09-25-lm-chains-hearts-rules-dictation',
    date: '2026-09-25',
    icon: '❤️',
    title: 'Word Chains, Heart Words, Spelling Rules, and Dictation',
    body: 'Four new things in Literacy Manipulatives: Word Chains (words that change one letter at a time), Heart Words (drag a tricky word and tap its letters to mark them with a heart), Spelling Rules (hover a card to read the rule), and a Dictation Card where you hear a word, write it, then reveal to check yourself.',
  },
  {
    id: '2026-09-25-trains-shipped',
    date: '2026-09-25',
    icon: '🚂',
    title: 'You can drive a train now',
    body: 'Find a train on some track and click it to hop aboard. Use the Go, Stop, and Reverse buttons to ride the rails, no steering needed, the track does that for you. Click the train again to hop off.',
  },
  {
    id: '2026-09-25-lm-phono-elkonin',
    date: '2026-09-25',
    icon: '🔊',
    title: 'New sound tools: chips, dividers, and a syllable tapper',
    body: 'Literacy Manipulatives has a new Phonological Awareness category with sound chips, an onset-rime divider bar, and a Syllable Tapper you can type or speak a word into and tap once per clap. Sound Boxes can also grow or shrink now, up to 8 boxes, with the +/- buttons that show when you select one.',
  },
  {
    id: '2026-09-25-lm-print-projector',
    date: '2026-09-25',
    icon: '🖨️',
    title: 'Print your board or go big for the class',
    body: 'Literacy Manipulatives now has a Print button that prints your board, and a Projector Mode button that makes everything bigger and easier to see from across the room.',
  },
  {
    id: '2026-09-25-lm-morpheme-spelling-rule',
    date: '2026-09-25',
    icon: '✂️',
    title: 'Spelling changes show up when word parts join',
    body: 'When you connect morpheme pieces that make a real word, sometimes the spelling changes a little, like the silent e dropping in "care" plus "-ing" makes "caring." Now a little badge pops up right where the pieces meet to show you.',
  },
  {
    id: '2026-09-25-lm-grapheme-colors-connector',
    date: '2026-09-25',
    icon: '🎨',
    title: 'Vowel and consonant colors, plus connector letters',
    body: 'Alphabet and Grapheme tiles now have a "Vowel/consonant colors" button that colors vowels red and consonants blue. Split-vowel tiles like a_e now show a little curved line connecting the two letters instead of a plain underscore.',
  },
  {
    id: '2026-09-25-lm-listening-chime',
    date: '2026-09-25',
    icon: '🎙️',
    title: 'A little chime when the microphone starts',
    body: 'When you tap the microphone button in Literacy Manipulatives, you now hear a little chime letting you know it is listening, and another one when it stops.',
  },
  {
    id: '2026-09-25-lm-punctuation-tiles',
    date: '2026-09-25',
    icon: '❓',
    title: 'New Punctuation tiles',
    body: 'Some students now have a Punctuation category in Literacy Manipulatives with tiles for periods, question marks, commas, and more. Hover over a tile to see what it does. Ask your teacher if you do not see it and want it.',
  },
  {
    id: '2026-09-25-boats-splash-sound',
    date: '2026-09-25',
    icon: '⛵',
    title: 'Boats have splash and engine sound now',
    body: 'Sail a boat and you will hear a soft engine sound and see a splash trail behind you that gets bigger the faster you go, plus a gentle bump sound near a dock or shore. Check Settings if you want to turn vehicle sound off, or turn on Reduce Motion to turn off the splash trail.',
  },
  {
    id: '2026-09-25-marketplace-amazon-look',
    date: '2026-09-25',
    icon: '🛍️',
    title: 'Marketplace has a new look',
    body: 'The Marketplace now has a sidebar on the side to pick what you want to shop for, and bigger item cards with a big Add to Cart button on each one. Searching and filtering still work just like before.',
  },
  {
    id: '2026-09-25-computer-laptop-look',
    date: '2026-09-25',
    icon: '💻',
    title: 'More screens look like real webpages now',
    body: 'Cinema, Arcade, Gallery, Farmer\'s Market, and Silly Quizzes all show up inside the laptop screen look now, with the same Back button as everywhere else on your Computer. Chat has a browser-style bar at the top too.',
  },
  {
    id: '2026-09-25-lm-synced-tts',
    date: '2026-09-25',
    icon: '🔈',
    title: 'Words light up when they are read aloud',
    body: 'In Literacy Manipulatives, when you tap a 🔈 button on a word list, a morpheme card, or a finished Sentence Formula sentence, the word being spoken lights up as it is read. It works on most devices; on a few it will still read aloud, just without the light-up.',
  },
  {
    id: '2026-09-25-lm-new-symbols',
    date: '2026-09-25',
    icon: '🔺',
    title: 'Brand new Grammar Symbols look',
    body: 'Grammar Symbols got a whole new set of pictures and colors! Noun is a red triangle now, verb is a green circle, pronoun is a yellow upside-down triangle, and more. The new look shows up everywhere symbols do, including Symbol Sentences.',
  },
  {
    id: '2026-09-24-lm-keyboard-delete',
    date: '2026-09-24',
    icon: '⌫',
    title: 'Delete key removes a selected item',
    body: 'Select something on your Literacy Manipulatives board and press Backspace or Delete on your keyboard to remove it, same as tapping the X.',
  },
  {
    id: '2026-09-24-lm-shape-settings-textfield',
    date: '2026-09-24',
    icon: '⚙️',
    title: 'Grammar Symbols can get their own text field',
    body: 'Select a Grammar Symbol on your board and a settings button shows up next to the X. Tap it and choose "Add a text field" to drop a real text box right next to the symbol, so you can write in your own word.',
  },
  {
    id: '2026-09-24-lm-formulas-symbol-sentences',
    date: '2026-09-24',
    icon: '🧷',
    title: 'Sentence Formulas move now, and more Literacy Manipulatives fixes',
    body: 'You can drag a Sentence Formula card around by its title now, and drop one right under another to join them into a paragraph. Symbol Sentences move as one piece now, and tap the little symbols row to see its settings, where you can type in the real words. Letters and graphemes snap right into Sound Boxes. The X to delete something only shows up once you pick it or tap it, so your board looks cleaner. Grammar Symbols in the side list are a bit smaller so more fits on screen, and Symbol Sentences are grouped with names like Descriptive and Complex Sentences instead of page numbers.',
  },
  {
    id: '2026-09-23-lm-tense-symbols',
    date: '2026-09-23',
    icon: '🔺',
    title: 'Bigger symbols, sentence settings, and hover hints',
    body: 'Grammar Symbols are twice as big now. Hover or tap and hold on a symbol to see its name and what it means. Sentence Formulas have two new buttons next to the X: a gear for settings (change your sentence to past, present, or future, and your words update to match) and a copy button to duplicate a formula with all your words still in it.',
  },
  {
    id: '2026-09-23-lm-paragraphs',
    date: '2026-09-23',
    icon: '📋',
    title: 'Build paragraphs with Sentence Formulas',
    body: 'Finish a Sentence Formula and it now shows your full sentence in a box, capitalized and ready. Tap "Add to paragraph" to send it to a text box, and keep adding more sentences to build a whole paragraph. The check now looks at capital letters too. Word lists in the dropdowns are in ABC order now, scroll to see more, and you can type the start of a word to find it fast. Dropdowns and text boxes both have a microphone button to talk instead of typing.',
  },
  {
    id: '2026-09-23-lm-grammar-check-more',
    date: '2026-09-23',
    icon: '✅',
    title: 'Sentence check and more fixes in Literacy Manipulatives',
    body: 'Fill in a whole Sentence Formula and a new card checks your words and tells you exactly what to fix, with a speaker button to hear it. Morpheme word definitions now have a speaker button too. Puzzle pieces click together better. Graphemes are sorted into groups now instead of one long list. You can drag something back onto the left side to delete it. The voice picker no longer shows a confusing "My Voice" option.',
  },
  {
    id: '2026-09-23-lm-zoom-delete',
    date: '2026-09-23',
    icon: '🔍',
    title: 'Zoom and delete in Literacy Manipulatives',
    body: 'Use the new zoom buttons at the top to make your board bigger or smaller. Every symbol, letter, and tile now has a small X on it so you can delete just that one thing. Sound Frames is now called Sound Boxes, and letters always show up in front of the boxes now. There is also a quick Text button right next to Draw.',
  },
  {
    id: '2026-09-23-lm-text-box',
    date: '2026-09-23',
    icon: '⌨️',
    title: 'New Text Box in Literacy Manipulatives',
    body: 'Tap Text Box on the left and drag it onto your board. Double-tap it to type, or tap the microphone to talk instead. You can also make the words bigger or smaller.',
  },
  {
    id: '2026-09-23-lm-drag-fix',
    date: '2026-09-23',
    icon: '🔧',
    title: 'Fixed dragging in Literacy Manipulatives',
    body: 'Dragging things from the left side onto your board is working right again.',
  },
  {
    id: '2026-09-23-lm-symbol-sentences',
    date: '2026-09-23',
    icon: '📜',
    title: 'New Symbol Sentences in Literacy Manipulatives',
    body: 'Tap Symbol Sentences on the left to see ready-made sentence cards made of just symbols. Drag one onto your board and its whole row of symbols comes with it. Once it is on your board you can pull the symbols apart and move them just like any other symbol.',
  },
  {
    id: '2026-09-23-lm-grammar-symbols-real',
    date: '2026-09-23',
    icon: '🔺',
    title: 'Real grammar symbol pictures in Literacy Manipulatives',
    body: 'Grammar Shapes is now called Grammar Symbols, and its tiles show the real symbol pictures instead of plain drawn shapes. The morpheme puzzle pieces got a new look too, with a little bump on top like a real puzzle piece. Word Lists can now be dragged onto your board too, not just tapped to hear, and the tool list on the left scrolls properly now so you can always see every section. The Sentence Grammar section is taking a short break and will be back later.',
  },
  {
    id: '2026-09-22-lm-save-toolbar',
    date: '2026-09-22',
    icon: '💾',
    title: 'Save your Literacy Manipulatives board!',
    body: 'Tap "Save" at the top to name and save your board, then find it again anytime in "My Boards." There is also a Redo button now next to Undo, and you can tap "Hide bar" to get more room to work.',
  },
  {
    id: '2026-09-22-lm-redesign',
    date: '2026-09-22',
    icon: '🧩',
    title: 'Literacy Manipulatives got a big redesign!',
    body: 'Everything is on one board now. Tap a tool on the left, like Alphabet, Grammar Shapes, Morphemes, Graphemes, Sound Frames, or Sentence Formulas, and drag it anywhere. Double-tap a letter to flip it upper or lower case. Morpheme puzzle pieces click together and show you the word\'s meaning when they spell something real. Draw and Mark are one button now, with a highlighter too.',
  },
  {
    id: '2026-09-22-sound-wall',
    date: '2026-09-22',
    icon: '🧱',
    title: 'New Sound Wall in My Tools!',
    body: 'Tap any sound to hear it, see the letters that spell it, how your mouth makes it, and a list of words with that sound. Tap Close to go back.',
  },
  {
    id: '2026-09-22-read-highlight',
    date: '2026-09-22',
    icon: '🔈',
    title: 'New: hear any part you highlight in Articles!',
    body: 'Select some text in an Article and tap "Read it" to hear just that part. Already saved a highlight? Open it and tap "Read this part."',
  },
  {
    id: '2026-09-22-lm-sidebar-collapse',
    date: '2026-09-22',
    icon: '🧩',
    title: 'Literacy Manipulatives sidebar is tidier now',
    body: 'Tap a section like "Naming words" or "Action words" to open just that one, instead of seeing everything at once.',
  },
  {
    id: '2026-09-22-nav-buttons-clean',
    date: '2026-09-22',
    icon: '🕹️',
    title: 'Driving and walking buttons are easier to hold now',
    body: 'Holding down a move button, or the gas and brake, used to sometimes pop up a copy menu on your screen and stop you from moving. Fixed! The buttons are icons only now, no more getting stuck.',
  },
  {
    id: '2026-09-22-solid-everywhere',
    date: '2026-09-22',
    icon: '🧱',
    title: 'Everything you place is solid now, everywhere',
    body: 'In your Home Room, furniture you bought from the Marketplace now stops you from walking through it too, just like everywhere else.',
  },
  {
    id: '2026-09-22-unstuck',
    date: '2026-09-22',
    icon: '🚶',
    title: 'No more getting stuck next to things',
    body: 'If you brushed up against something while walking or driving, you could sometimes get a little stuck. Fixed in Town Square, Creative Island, and your Home Room.',
  },
  {
    id: '2026-09-22-pet-more-colors',
    date: '2026-09-22',
    icon: '🎨',
    title: 'More pet colors to pick from',
    body: 'Your pet’s Color row now has a "more colors" option too, not just the 12 squares, so you can pick any color you want.',
  },
  {
    id: '2026-09-22-music-fixed',
    date: '2026-09-22',
    icon: '🎶',
    title: 'Skipping songs works right now',
    body: 'Next and Previous on the music player were not working. Fixed!',
  },
  {
    id: '2026-09-22-auto-questions',
    date: '2026-09-22',
    icon: '🧠',
    title: 'New practice questions for gas refills',
    body: 'If there are not enough questions loaded yet, you might get a math fact or a word-parts question instead, so you can always keep playing.',
  },
  {
    id: '2026-09-22-laptop-screens',
    date: '2026-09-22',
    icon: '💻',
    title: 'The Bank, Mail, and Marketplace look like a real computer now',
    body: 'Those screens show up inside a laptop now, just like your Computer at home already did. Same look everywhere you go.',
  },
  {
    id: '2026-09-22-music-background',
    date: '2026-09-22',
    icon: '🎵',
    title: 'Music keeps playing now!',
    body: 'Pick a song from the radio, Concert Hall, or Boom Box, and it keeps playing even after you leave Town Square, like while you are doing an assignment. Look for the little music button in the corner. Tap it to see the full controls.',
  },
  {
    id: '2026-09-22-gas-pump',
    date: '2026-09-22',
    icon: '⛽',
    title: 'Fill up your car with a Gas Pump!',
    body: 'Cars use gas now while you drive. If you find a Gas Pump in Town Square, walk up and tap it to answer a question and fill your tank. You can also tap the gas gauge at the top of the screen any time.',
  },
  {
    id: '2026-09-22-driving-fixed',
    date: '2026-09-22',
    icon: '🚗',
    title: 'Driving feels right now',
    body: 'Left and right were switched while driving a car or boat. Fixed! Turning now goes the way you expect.',
  },
  {
    id: '2026-09-22-solid-things',
    date: '2026-09-22',
    icon: '🧱',
    title: 'Things in Town Square are solid now',
    body: 'Buildings, trees, and everything else placed in Town Square now stop you from walking or driving through them, just like real things do.',
  },
  {
    id: '2026-09-22-sky-fixed',
    date: '2026-09-22',
    icon: '☀️',
    title: 'The sky looks right again',
    body: 'The sky is one clean color now, no more weird shapes.',
  },
  {
    id: '2026-09-16-camera-look-up-down',
    date: '2026-09-16',
    icon: '🔭',
    title: 'Look up and down now too!',
    body: 'The camera can tilt up and down while you play, not just side to side. Use the new Up and Down buttons, or drag with your mouse.',
  },
  {
    id: '2026-09-16-pie-menu',
    date: '2026-09-16',
    icon: '🧭',
    title: 'Tap yourself for a quick menu!',
    body: 'Tap your own character to open a quick menu for Settings, the Map, My Stuff, and My Home. No more hunting around the screen for buttons.',
  },
  {
    id: '2026-09-16-pet-book',
    date: '2026-09-16',
    icon: '🐾',
    title: 'A new Pet Book!',
    body: 'Open your backpack and look for the Pet Book. Flip through every pet you own, just like the Joke Book.',
  },
  {
    id: '2026-09-16-pet-walk',
    date: '2026-09-16',
    icon: '🐶',
    title: 'Pets walk beside you the right size now',
    body: 'Your pet companion is properly sized next to you now, and turns to face the same way you do while it walks along beside you.',
  },
  {
    id: '2026-09-16-island',
    date: '2026-09-16',
    icon: '🏝️',
    title: 'A brand new Creative Island!',
    body: 'Ask your teacher to unlock your very own Creative Island, a free-build space where you can place anything from the whole catalog, no limits.',
  },
  {
    id: '2026-09-16-wizard',
    date: '2026-09-16',
    icon: '⚡',
    title: 'Meet Wizard ThunderSword',
    body: 'If you’ve been playing a long time without working on your assignments, Wizard ThunderSword will fly in to help point you back to what you still need to do.',
  },
];

export const LATEST_CHANGELOG_ID = CHANGELOG_ENTRIES[0]?.id ?? null;

export function hasUnseenChangelog(lastSeenId: string | null | undefined): boolean {
  return !!LATEST_CHANGELOG_ID && lastSeenId !== LATEST_CHANGELOG_ID;
}
