/**
 * Common Core State Standards (CCSS) reference data for Math and
 * English Language Arts/Literacy, grades K-8.
 *
 * This is a curated, representative subset (not the full standard set,
 * which runs to several hundred entries per subject) chosen to cover the
 * standards a K-8 teacher would most commonly reference for a daily or
 * weekly instructional focus. Descriptions are drawn directly from the
 * official standard text and trimmed for length by dropping sub-clauses
 * (e.g. trailing examples or lettered sub-standards), not by rewording.
 *
 * Source verified against the official Common Core State Standards
 * Initiative site (thecorestandards.org / corestandards.org), September 2026.
 */

export interface CommonCoreStandard {
  code: string; // official CCSS code, e.g. "CCSS.MATH.CONTENT.3.OA.A.1" or "CCSS.ELA-LITERACY.RF.2.3"
  grade: string; // e.g. "K", "1", "2", ..., "8", or "K-5" for a foundational-skills band if that's how it's organized
  domain: string; // short domain name, e.g. "Operations & Algebraic Thinking", "Reading: Foundational Skills"
  description: string; // the actual standard text, kept to one sentence
}

export const MATH_STANDARDS: CommonCoreStandard[] = [
  // ---- Kindergarten ----
  { code: "CCSS.MATH.CONTENT.K.CC.A.1", grade: "K", domain: "Counting & Cardinality", description: "Count to 100 by ones and by tens." },
  { code: "CCSS.MATH.CONTENT.K.CC.A.3", grade: "K", domain: "Counting & Cardinality", description: "Write numbers from 0 to 20; represent a number of objects with a written numeral 0-20." },
  { code: "CCSS.MATH.CONTENT.K.CC.B.4", grade: "K", domain: "Counting & Cardinality", description: "Understand the relationship between numbers and quantities; connect counting to cardinality." },
  { code: "CCSS.MATH.CONTENT.K.CC.B.5", grade: "K", domain: "Counting & Cardinality", description: "Count to answer 'how many?' questions about as many as 20 things arranged in a line, array, or circle." },
  { code: "CCSS.MATH.CONTENT.K.CC.C.6", grade: "K", domain: "Counting & Cardinality", description: "Identify whether the number of objects in one group is greater than, less than, or equal to the number of objects in another group." },
  { code: "CCSS.MATH.CONTENT.K.OA.A.1", grade: "K", domain: "Operations & Algebraic Thinking", description: "Represent addition and subtraction with objects, fingers, mental images, drawings, sounds, acting out situations, verbal explanations, expressions, or equations." },
  { code: "CCSS.MATH.CONTENT.K.OA.A.2", grade: "K", domain: "Operations & Algebraic Thinking", description: "Solve addition and subtraction word problems, and add and subtract within 10." },
  { code: "CCSS.MATH.CONTENT.K.OA.A.3", grade: "K", domain: "Operations & Algebraic Thinking", description: "Decompose numbers less than or equal to 10 into pairs in more than one way." },
  { code: "CCSS.MATH.CONTENT.K.OA.A.4", grade: "K", domain: "Operations & Algebraic Thinking", description: "For any number 1-9, find the number that makes 10 when added to the given number." },
  { code: "CCSS.MATH.CONTENT.K.OA.A.5", grade: "K", domain: "Operations & Algebraic Thinking", description: "Fluently add and subtract within 5." },
  { code: "CCSS.MATH.CONTENT.K.NBT.A.1", grade: "K", domain: "Number & Operations in Base Ten", description: "Compose and decompose numbers from 11 to 19 into ten ones and some further ones." },
  { code: "CCSS.MATH.CONTENT.K.MD.A.1", grade: "K", domain: "Measurement & Data", description: "Describe measurable attributes of objects, such as length or weight." },
  { code: "CCSS.MATH.CONTENT.K.MD.A.2", grade: "K", domain: "Measurement & Data", description: "Directly compare two objects with a measurable attribute in common, to see which object has 'more of'/'less of' the attribute." },
  { code: "CCSS.MATH.CONTENT.K.MD.B.3", grade: "K", domain: "Measurement & Data", description: "Classify objects into given categories; count the numbers of objects in each category and sort the categories by count." },
  { code: "CCSS.MATH.CONTENT.K.G.A.1", grade: "K", domain: "Geometry", description: "Describe objects in the environment using names of shapes, and describe the relative positions of these objects." },
  { code: "CCSS.MATH.CONTENT.K.G.A.2", grade: "K", domain: "Geometry", description: "Correctly name shapes regardless of their orientations or overall size." },
  { code: "CCSS.MATH.CONTENT.K.G.B.4", grade: "K", domain: "Geometry", description: "Analyze and compare two- and three-dimensional shapes, in different sizes and orientations." },
  { code: "CCSS.MATH.CONTENT.K.G.B.5", grade: "K", domain: "Geometry", description: "Model shapes in the world by building shapes from components and drawing shapes." },

  // ---- Grade 1 ----
  { code: "CCSS.MATH.CONTENT.1.OA.A.1", grade: "1", domain: "Operations & Algebraic Thinking", description: "Use addition and subtraction within 20 to solve word problems involving situations of adding to, taking from, putting together, taking apart, and comparing." },
  { code: "CCSS.MATH.CONTENT.1.OA.B.3", grade: "1", domain: "Operations & Algebraic Thinking", description: "Apply properties of operations as strategies to add and subtract." },
  { code: "CCSS.MATH.CONTENT.1.OA.C.5", grade: "1", domain: "Operations & Algebraic Thinking", description: "Relate counting to addition and subtraction." },
  { code: "CCSS.MATH.CONTENT.1.OA.C.6", grade: "1", domain: "Operations & Algebraic Thinking", description: "Add and subtract within 20, demonstrating fluency for addition and subtraction within 10." },
  { code: "CCSS.MATH.CONTENT.1.OA.D.8", grade: "1", domain: "Operations & Algebraic Thinking", description: "Determine the unknown whole number in an addition or subtraction equation relating three whole numbers." },
  { code: "CCSS.MATH.CONTENT.1.NBT.A.1", grade: "1", domain: "Number & Operations in Base Ten", description: "Count to 120, starting at any number less than 120." },
  { code: "CCSS.MATH.CONTENT.1.NBT.B.2", grade: "1", domain: "Number & Operations in Base Ten", description: "Understand that the two digits of a two-digit number represent amounts of tens and ones." },
  { code: "CCSS.MATH.CONTENT.1.NBT.C.4", grade: "1", domain: "Number & Operations in Base Ten", description: "Add within 100, including adding a two-digit number and a one-digit number, and a two-digit number and a multiple of 10." },
  { code: "CCSS.MATH.CONTENT.1.NBT.C.6", grade: "1", domain: "Number & Operations in Base Ten", description: "Subtract multiples of 10 in the range 10-90 from multiples of 10 in the range 10-90." },
  { code: "CCSS.MATH.CONTENT.1.MD.A.1", grade: "1", domain: "Measurement & Data", description: "Order three objects by length; compare the lengths of two objects indirectly by using a third object." },
  { code: "CCSS.MATH.CONTENT.1.MD.B.3", grade: "1", domain: "Measurement & Data", description: "Tell and write time in hours and half-hours using analog and digital clocks." },
  { code: "CCSS.MATH.CONTENT.1.MD.C.4", grade: "1", domain: "Measurement & Data", description: "Organize, represent, and interpret data with up to three categories." },
  { code: "CCSS.MATH.CONTENT.1.G.A.1", grade: "1", domain: "Geometry", description: "Distinguish between defining attributes versus non-defining attributes for a wide variety of shapes." },
  { code: "CCSS.MATH.CONTENT.1.G.A.2", grade: "1", domain: "Geometry", description: "Compose two-dimensional shapes or three-dimensional shapes to create a composite shape." },
  { code: "CCSS.MATH.CONTENT.1.G.A.3", grade: "1", domain: "Geometry", description: "Partition circles and rectangles into two and four equal shares." },

  // ---- Grade 2 ----
  { code: "CCSS.MATH.CONTENT.2.OA.A.1", grade: "2", domain: "Operations & Algebraic Thinking", description: "Use addition and subtraction within 100 to solve one- and two-step word problems." },
  { code: "CCSS.MATH.CONTENT.2.OA.B.2", grade: "2", domain: "Operations & Algebraic Thinking", description: "Fluently add and subtract within 20 using mental strategies." },
  { code: "CCSS.MATH.CONTENT.2.OA.C.3", grade: "2", domain: "Operations & Algebraic Thinking", description: "Determine whether a group of objects (up to 20) has an odd or even number of members." },
  { code: "CCSS.MATH.CONTENT.2.OA.C.4", grade: "2", domain: "Operations & Algebraic Thinking", description: "Use addition to find the total number of objects arranged in rectangular arrays with up to 5 rows and 5 columns." },
  { code: "CCSS.MATH.CONTENT.2.NBT.A.1", grade: "2", domain: "Number & Operations in Base Ten", description: "Understand that the three digits of a three-digit number represent amounts of hundreds, tens, and ones." },
  { code: "CCSS.MATH.CONTENT.2.NBT.A.2", grade: "2", domain: "Number & Operations in Base Ten", description: "Count within 1000; skip-count by 5s, 10s, and 100s." },
  { code: "CCSS.MATH.CONTENT.2.NBT.B.5", grade: "2", domain: "Number & Operations in Base Ten", description: "Fluently add and subtract within 100 using strategies based on place value, properties of operations, and/or the relationship between addition and subtraction." },
  { code: "CCSS.MATH.CONTENT.2.NBT.B.7", grade: "2", domain: "Number & Operations in Base Ten", description: "Add and subtract within 1000, using concrete models or drawings and strategies based on place value." },
  { code: "CCSS.MATH.CONTENT.2.MD.A.1", grade: "2", domain: "Measurement & Data", description: "Measure the length of an object by selecting and using appropriate tools." },
  { code: "CCSS.MATH.CONTENT.2.MD.C.7", grade: "2", domain: "Measurement & Data", description: "Tell and write time from analog and digital clocks to the nearest five minutes, using a.m. and p.m." },
  { code: "CCSS.MATH.CONTENT.2.MD.C.8", grade: "2", domain: "Measurement & Data", description: "Solve word problems involving dollar bills, quarters, dimes, nickels, and pennies." },
  { code: "CCSS.MATH.CONTENT.2.MD.D.10", grade: "2", domain: "Measurement & Data", description: "Draw a picture graph and a bar graph to represent a data set with up to four categories." },
  { code: "CCSS.MATH.CONTENT.2.G.A.1", grade: "2", domain: "Geometry", description: "Recognize and draw shapes having specified attributes, such as a given number of angles or a given number of equal faces." },
  { code: "CCSS.MATH.CONTENT.2.G.A.3", grade: "2", domain: "Geometry", description: "Partition circles and rectangles into two, three, or four equal shares." },

  // ---- Grade 3 ----
  { code: "CCSS.MATH.CONTENT.3.OA.A.1", grade: "3", domain: "Operations & Algebraic Thinking", description: "Interpret products of whole numbers, e.g., interpret 5 x 7 as the total number of objects in 5 groups of 7 objects each." },
  { code: "CCSS.MATH.CONTENT.3.OA.A.3", grade: "3", domain: "Operations & Algebraic Thinking", description: "Use multiplication and division within 100 to solve word problems in situations involving equal groups, arrays, and measurement quantities." },
  { code: "CCSS.MATH.CONTENT.3.OA.C.7", grade: "3", domain: "Operations & Algebraic Thinking", description: "Fluently multiply and divide within 100, using strategies such as the relationship between multiplication and division." },
  { code: "CCSS.MATH.CONTENT.3.OA.D.8", grade: "3", domain: "Operations & Algebraic Thinking", description: "Solve two-step word problems using the four operations." },
  { code: "CCSS.MATH.CONTENT.3.NBT.A.1", grade: "3", domain: "Number & Operations in Base Ten", description: "Use place value understanding to round whole numbers to the nearest 10 or 100." },
  { code: "CCSS.MATH.CONTENT.3.NBT.A.2", grade: "3", domain: "Number & Operations in Base Ten", description: "Fluently add and subtract within 1000 using strategies and algorithms based on place value, properties of operations, and/or the relationship between addition and subtraction." },
  { code: "CCSS.MATH.CONTENT.3.NBT.A.3", grade: "3", domain: "Number & Operations in Base Ten", description: "Multiply one-digit whole numbers by multiples of 10 in the range 10-90." },
  { code: "CCSS.MATH.CONTENT.3.NF.A.1", grade: "3", domain: "Number and Operations: Fractions", description: "Understand a fraction 1/b as the quantity formed by 1 part when a whole is partitioned into b equal parts." },
  { code: "CCSS.MATH.CONTENT.3.NF.A.2", grade: "3", domain: "Number and Operations: Fractions", description: "Understand a fraction as a number on the number line; represent fractions on a number line diagram." },
  { code: "CCSS.MATH.CONTENT.3.NF.A.3", grade: "3", domain: "Number and Operations: Fractions", description: "Explain equivalence of fractions in special cases, and compare fractions by reasoning about their size." },
  { code: "CCSS.MATH.CONTENT.3.MD.A.1", grade: "3", domain: "Measurement & Data", description: "Tell and write time to the nearest minute and measure time intervals in minutes." },
  { code: "CCSS.MATH.CONTENT.3.MD.B.3", grade: "3", domain: "Measurement & Data", description: "Draw a scaled picture graph and a scaled bar graph to represent a data set with several categories." },
  { code: "CCSS.MATH.CONTENT.3.MD.C.7", grade: "3", domain: "Measurement & Data", description: "Relate area to the operations of multiplication and addition." },
  { code: "CCSS.MATH.CONTENT.3.MD.D.8", grade: "3", domain: "Measurement & Data", description: "Solve real world and mathematical problems involving perimeters of polygons." },
  { code: "CCSS.MATH.CONTENT.3.G.A.1", grade: "3", domain: "Geometry", description: "Understand that shapes in different categories may share attributes, and that the shared attributes can define a larger category." },
  { code: "CCSS.MATH.CONTENT.3.G.A.2", grade: "3", domain: "Geometry", description: "Partition shapes into parts with equal areas, and express the area of each part as a unit fraction of the whole." },

  // ---- Grade 4 ----
  { code: "CCSS.MATH.CONTENT.4.OA.A.1", grade: "4", domain: "Operations & Algebraic Thinking", description: "Interpret a multiplication equation as a comparison, e.g., interpret 35 = 5 x 7 as a statement that 35 is 5 times as many as 7 and 7 times as many as 5." },
  { code: "CCSS.MATH.CONTENT.4.OA.A.3", grade: "4", domain: "Operations & Algebraic Thinking", description: "Solve multistep word problems posed with whole numbers and having whole-number answers using the four operations." },
  { code: "CCSS.MATH.CONTENT.4.OA.B.4", grade: "4", domain: "Operations & Algebraic Thinking", description: "Find all factor pairs for a whole number in the range 1-100." },
  { code: "CCSS.MATH.CONTENT.4.OA.C.5", grade: "4", domain: "Operations & Algebraic Thinking", description: "Generate a number or shape pattern that follows a given rule." },
  { code: "CCSS.MATH.CONTENT.4.NBT.A.1", grade: "4", domain: "Number & Operations in Base Ten", description: "Recognize that in a multi-digit whole number, a digit in one place represents ten times what it represents in the place to its right." },
  { code: "CCSS.MATH.CONTENT.4.NBT.A.2", grade: "4", domain: "Number & Operations in Base Ten", description: "Read and write multi-digit whole numbers using base-ten numerals, number names, and expanded form." },
  { code: "CCSS.MATH.CONTENT.4.NBT.B.4", grade: "4", domain: "Number & Operations in Base Ten", description: "Fluently add and subtract multi-digit whole numbers using the standard algorithm." },
  { code: "CCSS.MATH.CONTENT.4.NBT.B.5", grade: "4", domain: "Number & Operations in Base Ten", description: "Multiply a whole number of up to four digits by a one-digit whole number, and multiply two two-digit numbers." },
  { code: "CCSS.MATH.CONTENT.4.NBT.B.6", grade: "4", domain: "Number & Operations in Base Ten", description: "Find whole-number quotients and remainders with up to four-digit dividends and one-digit divisors." },
  { code: "CCSS.MATH.CONTENT.4.NF.A.1", grade: "4", domain: "Number and Operations: Fractions", description: "Explain why a fraction a/b is equivalent to a fraction (n x a)/(n x b) by using visual fraction models." },
  { code: "CCSS.MATH.CONTENT.4.NF.B.3", grade: "4", domain: "Number and Operations: Fractions", description: "Understand a fraction a/b with a > 1 as a sum of fractions 1/b." },
  { code: "CCSS.MATH.CONTENT.4.NF.C.6", grade: "4", domain: "Number and Operations: Fractions", description: "Use decimal notation for fractions with denominators 10 or 100." },
  { code: "CCSS.MATH.CONTENT.4.MD.A.1", grade: "4", domain: "Measurement & Data", description: "Know relative sizes of measurement units within one system of units." },
  { code: "CCSS.MATH.CONTENT.4.MD.A.2", grade: "4", domain: "Measurement & Data", description: "Use the four operations to solve word problems involving distances, intervals of time, liquid volumes, masses of objects, and money." },
  { code: "CCSS.MATH.CONTENT.4.MD.C.5", grade: "4", domain: "Measurement & Data", description: "Recognize angles as geometric shapes that are formed wherever two rays share a common endpoint, and understand concepts of angle measurement." },
  { code: "CCSS.MATH.CONTENT.4.G.A.1", grade: "4", domain: "Geometry", description: "Draw points, lines, line segments, rays, angles, and perpendicular and parallel lines." },
  { code: "CCSS.MATH.CONTENT.4.G.A.2", grade: "4", domain: "Geometry", description: "Classify two-dimensional figures based on the presence or absence of parallel or perpendicular lines, or the presence or absence of angles of a specified size." },
  { code: "CCSS.MATH.CONTENT.4.G.A.3", grade: "4", domain: "Geometry", description: "Recognize a line of symmetry for a two-dimensional figure." },

  // ---- Grade 5 ----
  { code: "CCSS.MATH.CONTENT.5.OA.A.1", grade: "5", domain: "Operations & Algebraic Thinking", description: "Use parentheses, brackets, or braces in numerical expressions, and evaluate expressions with these symbols." },
  { code: "CCSS.MATH.CONTENT.5.OA.B.3", grade: "5", domain: "Operations & Algebraic Thinking", description: "Generate two numerical patterns using two given rules, and identify apparent relationships between corresponding terms." },
  { code: "CCSS.MATH.CONTENT.5.NBT.A.1", grade: "5", domain: "Number & Operations in Base Ten", description: "Recognize that in a multi-digit number, a digit in one place represents 10 times as much as it represents in the place to its right." },
  { code: "CCSS.MATH.CONTENT.5.NBT.A.3", grade: "5", domain: "Number & Operations in Base Ten", description: "Read, write, and compare decimals to thousandths." },
  { code: "CCSS.MATH.CONTENT.5.NBT.B.5", grade: "5", domain: "Number & Operations in Base Ten", description: "Fluently multiply multi-digit whole numbers using the standard algorithm." },
  { code: "CCSS.MATH.CONTENT.5.NBT.B.7", grade: "5", domain: "Number & Operations in Base Ten", description: "Add, subtract, multiply, and divide decimals to hundredths, using concrete models or drawings and strategies based on place value." },
  { code: "CCSS.MATH.CONTENT.5.NF.A.1", grade: "5", domain: "Number and Operations: Fractions", description: "Add and subtract fractions with unlike denominators (including mixed numbers) by replacing given fractions with equivalent fractions." },
  { code: "CCSS.MATH.CONTENT.5.NF.B.3", grade: "5", domain: "Number and Operations: Fractions", description: "Interpret a fraction as division of the numerator by the denominator." },
  { code: "CCSS.MATH.CONTENT.5.NF.B.4", grade: "5", domain: "Number and Operations: Fractions", description: "Apply and extend previous understandings of multiplication to multiply a fraction or whole number by a fraction." },
  { code: "CCSS.MATH.CONTENT.5.NF.B.7", grade: "5", domain: "Number and Operations: Fractions", description: "Apply and extend previous understandings of division to divide unit fractions by whole numbers and whole numbers by unit fractions." },
  { code: "CCSS.MATH.CONTENT.5.MD.A.1", grade: "5", domain: "Measurement & Data", description: "Convert among different-sized standard measurement units within a given measurement system." },
  { code: "CCSS.MATH.CONTENT.5.MD.B.2", grade: "5", domain: "Measurement & Data", description: "Make a line plot to display a data set of measurements in fractions of a unit." },
  { code: "CCSS.MATH.CONTENT.5.MD.C.3", grade: "5", domain: "Measurement & Data", description: "Recognize volume as an attribute of solid figures and understand concepts of volume measurement." },
  { code: "CCSS.MATH.CONTENT.5.MD.C.5", grade: "5", domain: "Measurement & Data", description: "Relate volume to the operations of multiplication and addition and solve real world and mathematical problems involving volume." },
  { code: "CCSS.MATH.CONTENT.5.G.A.1", grade: "5", domain: "Geometry", description: "Use a pair of perpendicular number lines, called axes, to define a coordinate system." },
  { code: "CCSS.MATH.CONTENT.5.G.A.2", grade: "5", domain: "Geometry", description: "Represent real world and mathematical problems by graphing points in the first quadrant of the coordinate plane." },
  { code: "CCSS.MATH.CONTENT.5.G.B.3", grade: "5", domain: "Geometry", description: "Understand that attributes belonging to a category of two-dimensional figures also belong to all subcategories of that category." },
  { code: "CCSS.MATH.CONTENT.5.G.B.4", grade: "5", domain: "Geometry", description: "Classify two-dimensional figures in a hierarchy based on properties." },

  // ---- Grade 6 ----
  { code: "CCSS.MATH.CONTENT.6.RP.A.1", grade: "6", domain: "Ratios & Proportional Relationships", description: "Understand the concept of a ratio and use ratio language to describe a ratio relationship between two quantities." },
  { code: "CCSS.MATH.CONTENT.6.RP.A.2", grade: "6", domain: "Ratios & Proportional Relationships", description: "Understand the concept of a unit rate a/b associated with a ratio a:b with b not equal to 0." },
  { code: "CCSS.MATH.CONTENT.6.RP.A.3", grade: "6", domain: "Ratios & Proportional Relationships", description: "Use ratio and rate reasoning to solve real-world and mathematical problems." },
  { code: "CCSS.MATH.CONTENT.6.NS.A.1", grade: "6", domain: "The Number System", description: "Interpret and compute quotients of fractions, and solve word problems involving division of fractions by fractions." },
  { code: "CCSS.MATH.CONTENT.6.NS.B.2", grade: "6", domain: "The Number System", description: "Fluently divide multi-digit numbers using the standard algorithm." },
  { code: "CCSS.MATH.CONTENT.6.NS.B.3", grade: "6", domain: "The Number System", description: "Fluently add, subtract, multiply, and divide multi-digit decimals using the standard algorithm for each operation." },
  { code: "CCSS.MATH.CONTENT.6.NS.C.5", grade: "6", domain: "The Number System", description: "Understand that positive and negative numbers are used together to describe quantities having opposite directions or values." },
  { code: "CCSS.MATH.CONTENT.6.NS.C.6", grade: "6", domain: "The Number System", description: "Understand a rational number as a point on the number line." },
  { code: "CCSS.MATH.CONTENT.6.EE.A.1", grade: "6", domain: "Expressions & Equations", description: "Write and evaluate numerical expressions involving whole-number exponents." },
  { code: "CCSS.MATH.CONTENT.6.EE.A.2", grade: "6", domain: "Expressions & Equations", description: "Write, read, and evaluate expressions in which letters stand for numbers." },
  { code: "CCSS.MATH.CONTENT.6.EE.B.5", grade: "6", domain: "Expressions & Equations", description: "Understand solving an equation or inequality as a process of answering a question." },
  { code: "CCSS.MATH.CONTENT.6.EE.B.7", grade: "6", domain: "Expressions & Equations", description: "Solve real-world and mathematical problems by writing and solving equations of the form x + p = q and px = q." },
  { code: "CCSS.MATH.CONTENT.6.EE.C.9", grade: "6", domain: "Expressions & Equations", description: "Use variables to represent two quantities in a real-world problem that change in relationship to one another." },
  { code: "CCSS.MATH.CONTENT.6.G.A.1", grade: "6", domain: "Geometry", description: "Find the area of right triangles, other triangles, special quadrilaterals, and polygons by composing into rectangles or decomposing into triangles and other shapes." },
  { code: "CCSS.MATH.CONTENT.6.G.A.2", grade: "6", domain: "Geometry", description: "Find the volume of a right rectangular prism with fractional edge lengths." },
  { code: "CCSS.MATH.CONTENT.6.SP.A.1", grade: "6", domain: "Statistics & Probability", description: "Recognize a statistical question as one that anticipates variability in the data related to the question." },
  { code: "CCSS.MATH.CONTENT.6.SP.B.4", grade: "6", domain: "Statistics & Probability", description: "Display numerical data in plots on a number line, including dot plots, histograms, and box plots." },
  { code: "CCSS.MATH.CONTENT.6.SP.B.5", grade: "6", domain: "Statistics & Probability", description: "Summarize numerical data sets in relation to their context." },

  // ---- Grade 7 ----
  { code: "CCSS.MATH.CONTENT.7.RP.A.1", grade: "7", domain: "Ratios & Proportional Relationships", description: "Compute unit rates associated with ratios of fractions, including ratios of lengths, areas and other quantities measured in like or different units." },
  { code: "CCSS.MATH.CONTENT.7.RP.A.2", grade: "7", domain: "Ratios & Proportional Relationships", description: "Recognize and represent proportional relationships between quantities." },
  { code: "CCSS.MATH.CONTENT.7.RP.A.3", grade: "7", domain: "Ratios & Proportional Relationships", description: "Use proportional relationships to solve multistep ratio and percent problems." },
  { code: "CCSS.MATH.CONTENT.7.NS.A.1", grade: "7", domain: "The Number System", description: "Apply and extend previous understandings of addition and subtraction to add and subtract rational numbers." },
  { code: "CCSS.MATH.CONTENT.7.NS.A.2", grade: "7", domain: "The Number System", description: "Apply and extend previous understandings of multiplication and division and of fractions to multiply and divide rational numbers." },
  { code: "CCSS.MATH.CONTENT.7.NS.A.3", grade: "7", domain: "The Number System", description: "Solve real-world and mathematical problems involving the four operations with rational numbers." },
  { code: "CCSS.MATH.CONTENT.7.EE.A.1", grade: "7", domain: "Expressions & Equations", description: "Apply properties of operations as strategies to add, subtract, factor, and expand linear expressions with rational coefficients." },
  { code: "CCSS.MATH.CONTENT.7.EE.B.3", grade: "7", domain: "Expressions & Equations", description: "Solve multi-step real-life and mathematical problems posed with positive and negative rational numbers in any form." },
  { code: "CCSS.MATH.CONTENT.7.EE.B.4", grade: "7", domain: "Expressions & Equations", description: "Use variables to represent quantities in a real-world or mathematical problem, and construct simple equations and inequalities to solve problems." },
  { code: "CCSS.MATH.CONTENT.7.G.A.1", grade: "7", domain: "Geometry", description: "Solve problems involving scale drawings of geometric figures." },
  { code: "CCSS.MATH.CONTENT.7.G.B.4", grade: "7", domain: "Geometry", description: "Know the formulas for the area and circumference of a circle and use them to solve problems." },
  { code: "CCSS.MATH.CONTENT.7.G.B.6", grade: "7", domain: "Geometry", description: "Solve real-world and mathematical problems involving area, volume and surface area of two- and three-dimensional objects." },
  { code: "CCSS.MATH.CONTENT.7.SP.A.1", grade: "7", domain: "Statistics & Probability", description: "Understand that statistics can be used to gain information about a population by examining a sample of the population." },
  { code: "CCSS.MATH.CONTENT.7.SP.C.5", grade: "7", domain: "Statistics & Probability", description: "Understand that the probability of a chance event is a number between 0 and 1 that expresses the likelihood of the event occurring." },
  { code: "CCSS.MATH.CONTENT.7.SP.C.8", grade: "7", domain: "Statistics & Probability", description: "Find probabilities of compound events using organized lists, tables, tree diagrams, and simulation." },

  // ---- Grade 8 ----
  { code: "CCSS.MATH.CONTENT.8.NS.A.1", grade: "8", domain: "The Number System", description: "Know that numbers that are not rational are called irrational." },
  { code: "CCSS.MATH.CONTENT.8.NS.A.2", grade: "8", domain: "The Number System", description: "Use rational approximations of irrational numbers to compare the size of irrational numbers." },
  { code: "CCSS.MATH.CONTENT.8.EE.A.1", grade: "8", domain: "Expressions & Equations", description: "Know and apply the properties of integer exponents to generate equivalent numerical expressions." },
  { code: "CCSS.MATH.CONTENT.8.EE.B.5", grade: "8", domain: "Expressions & Equations", description: "Graph proportional relationships, interpreting the unit rate as the slope of the graph." },
  { code: "CCSS.MATH.CONTENT.8.EE.C.7", grade: "8", domain: "Expressions & Equations", description: "Solve linear equations in one variable." },
  { code: "CCSS.MATH.CONTENT.8.EE.C.8", grade: "8", domain: "Expressions & Equations", description: "Analyze and solve pairs of simultaneous linear equations." },
  { code: "CCSS.MATH.CONTENT.8.F.A.1", grade: "8", domain: "Functions", description: "Understand that a function is a rule that assigns to each input exactly one output." },
  { code: "CCSS.MATH.CONTENT.8.F.A.2", grade: "8", domain: "Functions", description: "Compare properties of two functions each represented in a different way." },
  { code: "CCSS.MATH.CONTENT.8.F.B.4", grade: "8", domain: "Functions", description: "Construct a function to model a linear relationship between two quantities." },
  { code: "CCSS.MATH.CONTENT.8.G.A.2", grade: "8", domain: "Geometry", description: "Understand that a two-dimensional figure is congruent to another if the second can be obtained from the first by a sequence of rotations, reflections, and translations." },
  { code: "CCSS.MATH.CONTENT.8.G.B.7", grade: "8", domain: "Geometry", description: "Apply the Pythagorean Theorem to determine unknown side lengths in right triangles." },
  { code: "CCSS.MATH.CONTENT.8.G.C.9", grade: "8", domain: "Geometry", description: "Know the formulas for the volumes of cones, cylinders, and spheres and use them to solve real-world and mathematical problems." },
  { code: "CCSS.MATH.CONTENT.8.SP.A.1", grade: "8", domain: "Statistics & Probability", description: "Construct and interpret scatter plots for bivariate measurement data to investigate patterns of association." },
  { code: "CCSS.MATH.CONTENT.8.SP.A.2", grade: "8", domain: "Statistics & Probability", description: "Know that straight lines are widely used to model relationships between two quantitative variables." },
  { code: "CCSS.MATH.CONTENT.8.SP.A.3", grade: "8", domain: "Statistics & Probability", description: "Use the equation of a linear model to solve problems in the context of bivariate measurement data." },
];

export const LITERACY_STANDARDS: CommonCoreStandard[] = [
  // ---- Reading: Foundational Skills (K-5) ----
  { code: "CCSS.ELA-LITERACY.RF.K.1", grade: "K", domain: "Reading: Foundational Skills", description: "Demonstrate understanding of the organization and basic features of print." },
  { code: "CCSS.ELA-LITERACY.RF.K.2", grade: "K", domain: "Reading: Foundational Skills", description: "Demonstrate understanding of spoken words, syllables, and sounds (phonemes)." },
  { code: "CCSS.ELA-LITERACY.RF.K.3", grade: "K", domain: "Reading: Foundational Skills", description: "Know and apply grade-level phonics and word analysis skills in decoding words." },
  { code: "CCSS.ELA-LITERACY.RF.K.4", grade: "K", domain: "Reading: Foundational Skills", description: "Read emergent-reader texts with purpose and understanding." },
  { code: "CCSS.ELA-LITERACY.RF.1.2", grade: "1", domain: "Reading: Foundational Skills", description: "Demonstrate understanding of spoken words, syllables, and sounds (phonemes)." },
  { code: "CCSS.ELA-LITERACY.RF.1.3", grade: "1", domain: "Reading: Foundational Skills", description: "Know and apply grade-level phonics and word analysis skills in decoding words." },
  { code: "CCSS.ELA-LITERACY.RF.1.4", grade: "1", domain: "Reading: Foundational Skills", description: "Read with sufficient accuracy and fluency to support comprehension." },
  { code: "CCSS.ELA-LITERACY.RF.2.3", grade: "2", domain: "Reading: Foundational Skills", description: "Know and apply grade-level phonics and word analysis skills in decoding words." },
  { code: "CCSS.ELA-LITERACY.RF.2.4", grade: "2", domain: "Reading: Foundational Skills", description: "Read with sufficient accuracy and fluency to support comprehension." },
  { code: "CCSS.ELA-LITERACY.RF.3.3", grade: "3", domain: "Reading: Foundational Skills", description: "Know and apply grade-level phonics and word analysis skills in decoding words." },
  { code: "CCSS.ELA-LITERACY.RF.3.4", grade: "3", domain: "Reading: Foundational Skills", description: "Read with sufficient accuracy and fluency to support comprehension." },
  { code: "CCSS.ELA-LITERACY.RF.4.3", grade: "4", domain: "Reading: Foundational Skills", description: "Know and apply grade-level phonics and word analysis skills in decoding words." },
  { code: "CCSS.ELA-LITERACY.RF.4.4", grade: "4", domain: "Reading: Foundational Skills", description: "Read with sufficient accuracy and fluency to support comprehension." },
  { code: "CCSS.ELA-LITERACY.RF.5.3", grade: "5", domain: "Reading: Foundational Skills", description: "Know and apply grade-level phonics and word analysis skills in decoding words." },
  { code: "CCSS.ELA-LITERACY.RF.5.4", grade: "5", domain: "Reading: Foundational Skills", description: "Read with sufficient accuracy and fluency to support comprehension." },

  // ---- Reading: Literature (K-8) ----
  { code: "CCSS.ELA-LITERACY.RL.K.1", grade: "K", domain: "Reading: Literature", description: "With prompting and support, ask and answer questions about key details in a text." },
  { code: "CCSS.ELA-LITERACY.RL.K.2", grade: "K", domain: "Reading: Literature", description: "With prompting and support, retell familiar stories, including key details." },
  { code: "CCSS.ELA-LITERACY.RL.K.3", grade: "K", domain: "Reading: Literature", description: "With prompting and support, identify characters, settings, and major events in a story." },
  { code: "CCSS.ELA-LITERACY.RL.1.1", grade: "1", domain: "Reading: Literature", description: "Ask and answer questions about key details in a text." },
  { code: "CCSS.ELA-LITERACY.RL.1.2", grade: "1", domain: "Reading: Literature", description: "Retell stories, including key details, and demonstrate understanding of their central message or lesson." },
  { code: "CCSS.ELA-LITERACY.RL.1.3", grade: "1", domain: "Reading: Literature", description: "Describe characters, settings, and major events in a story, using key details." },
  { code: "CCSS.ELA-LITERACY.RL.2.1", grade: "2", domain: "Reading: Literature", description: "Ask and answer such questions as who, what, where, when, why, and how to demonstrate understanding of key details in a text." },
  { code: "CCSS.ELA-LITERACY.RL.2.2", grade: "2", domain: "Reading: Literature", description: "Recount stories, including fables and folktales from diverse cultures, and determine their central message, lesson, or moral." },
  { code: "CCSS.ELA-LITERACY.RL.2.3", grade: "2", domain: "Reading: Literature", description: "Describe how characters in a story respond to major events and challenges." },
  { code: "CCSS.ELA-LITERACY.RL.3.1", grade: "3", domain: "Reading: Literature", description: "Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers." },
  { code: "CCSS.ELA-LITERACY.RL.3.2", grade: "3", domain: "Reading: Literature", description: "Recount stories, including fables, folktales, and myths from diverse cultures; determine the central message, lesson, or moral." },
  { code: "CCSS.ELA-LITERACY.RL.3.3", grade: "3", domain: "Reading: Literature", description: "Describe characters in a story and explain how their actions contribute to the sequence of events." },
  { code: "CCSS.ELA-LITERACY.RL.4.1", grade: "4", domain: "Reading: Literature", description: "Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text." },
  { code: "CCSS.ELA-LITERACY.RL.4.2", grade: "4", domain: "Reading: Literature", description: "Determine a theme of a story, drama, or poem from details in the text; summarize the text." },
  { code: "CCSS.ELA-LITERACY.RL.4.3", grade: "4", domain: "Reading: Literature", description: "Describe in depth a character, setting, or event in a story or drama, drawing on specific details in the text." },
  { code: "CCSS.ELA-LITERACY.RL.5.1", grade: "5", domain: "Reading: Literature", description: "Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text." },
  { code: "CCSS.ELA-LITERACY.RL.5.2", grade: "5", domain: "Reading: Literature", description: "Determine a theme of a story, drama, or poem from details in the text, including how characters respond to challenges; summarize the text." },
  { code: "CCSS.ELA-LITERACY.RL.5.3", grade: "5", domain: "Reading: Literature", description: "Compare and contrast two or more characters, settings, or events in a story or drama, drawing on specific details in the text." },
  { code: "CCSS.ELA-LITERACY.RL.6.1", grade: "6", domain: "Reading: Literature", description: "Cite textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text." },
  { code: "CCSS.ELA-LITERACY.RL.6.2", grade: "6", domain: "Reading: Literature", description: "Determine a theme or central idea of a text and how it is conveyed through particular details; provide a summary of the text." },
  { code: "CCSS.ELA-LITERACY.RL.6.3", grade: "6", domain: "Reading: Literature", description: "Describe how a particular story's or drama's plot unfolds in a series of episodes as well as how the characters respond or change." },
  { code: "CCSS.ELA-LITERACY.RL.7.1", grade: "7", domain: "Reading: Literature", description: "Cite several pieces of textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text." },
  { code: "CCSS.ELA-LITERACY.RL.7.2", grade: "7", domain: "Reading: Literature", description: "Determine a theme or central idea of a text and analyze its development over the course of the text; provide an objective summary of the text." },
  { code: "CCSS.ELA-LITERACY.RL.7.3", grade: "7", domain: "Reading: Literature", description: "Analyze how particular elements of a story or drama interact." },
  { code: "CCSS.ELA-LITERACY.RL.8.1", grade: "8", domain: "Reading: Literature", description: "Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text." },
  { code: "CCSS.ELA-LITERACY.RL.8.2", grade: "8", domain: "Reading: Literature", description: "Determine a theme or central idea of a text and analyze its development over the course of the text." },
  { code: "CCSS.ELA-LITERACY.RL.8.3", grade: "8", domain: "Reading: Literature", description: "Analyze how particular lines of dialogue or incidents in a story or drama propel the action, reveal aspects of a character, or provoke a decision." },

  // ---- Reading: Informational Text (K-8) ----
  { code: "CCSS.ELA-LITERACY.RI.K.1", grade: "K", domain: "Reading: Informational Text", description: "With prompting and support, ask and answer questions about key details in a text." },
  { code: "CCSS.ELA-LITERACY.RI.K.2", grade: "K", domain: "Reading: Informational Text", description: "With prompting and support, identify the main topic and retell key details of a text." },
  { code: "CCSS.ELA-LITERACY.RI.K.3", grade: "K", domain: "Reading: Informational Text", description: "With prompting and support, describe the connection between two individuals, events, ideas, or pieces of information in a text." },
  { code: "CCSS.ELA-LITERACY.RI.1.1", grade: "1", domain: "Reading: Informational Text", description: "Ask and answer questions about key details in a text." },
  { code: "CCSS.ELA-LITERACY.RI.1.2", grade: "1", domain: "Reading: Informational Text", description: "Identify the main topic and retell key details of a text." },
  { code: "CCSS.ELA-LITERACY.RI.1.3", grade: "1", domain: "Reading: Informational Text", description: "Describe the connection between two individuals, events, ideas, or pieces of information in a text." },
  { code: "CCSS.ELA-LITERACY.RI.2.1", grade: "2", domain: "Reading: Informational Text", description: "Ask and answer such questions as who, what, where, when, why, and how to demonstrate understanding of key details in a text." },
  { code: "CCSS.ELA-LITERACY.RI.2.2", grade: "2", domain: "Reading: Informational Text", description: "Identify the main topic of a multiparagraph text as well as the focus of specific paragraphs within the text." },
  { code: "CCSS.ELA-LITERACY.RI.2.3", grade: "2", domain: "Reading: Informational Text", description: "Describe the connection between a series of historical events, scientific ideas or concepts, or steps in technical procedures in a text." },
  { code: "CCSS.ELA-LITERACY.RI.3.1", grade: "3", domain: "Reading: Informational Text", description: "Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers." },
  { code: "CCSS.ELA-LITERACY.RI.3.2", grade: "3", domain: "Reading: Informational Text", description: "Determine the main idea of a text; recount the key details and explain how they support the main idea." },
  { code: "CCSS.ELA-LITERACY.RI.3.3", grade: "3", domain: "Reading: Informational Text", description: "Describe the relationship between a series of historical events, scientific ideas or concepts, or steps in technical procedures in a text." },
  { code: "CCSS.ELA-LITERACY.RI.4.1", grade: "4", domain: "Reading: Informational Text", description: "Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text." },
  { code: "CCSS.ELA-LITERACY.RI.4.2", grade: "4", domain: "Reading: Informational Text", description: "Determine the main idea of a text and explain how it is supported by key details; summarize the text." },
  { code: "CCSS.ELA-LITERACY.RI.4.3", grade: "4", domain: "Reading: Informational Text", description: "Explain events, procedures, ideas, or concepts in a historical, scientific, or technical text." },
  { code: "CCSS.ELA-LITERACY.RI.5.1", grade: "5", domain: "Reading: Informational Text", description: "Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text." },
  { code: "CCSS.ELA-LITERACY.RI.5.2", grade: "5", domain: "Reading: Informational Text", description: "Determine two or more main ideas of a text and explain how they are supported by key details; summarize the text." },
  { code: "CCSS.ELA-LITERACY.RI.5.3", grade: "5", domain: "Reading: Informational Text", description: "Explain the relationships or interactions between two or more individuals, events, ideas, or concepts in a historical, scientific, or technical text." },
  { code: "CCSS.ELA-LITERACY.RI.6.1", grade: "6", domain: "Reading: Informational Text", description: "Cite textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text." },
  { code: "CCSS.ELA-LITERACY.RI.6.2", grade: "6", domain: "Reading: Informational Text", description: "Determine a central idea of a text and how it is conveyed through particular details; provide a summary of the text." },
  { code: "CCSS.ELA-LITERACY.RI.6.3", grade: "6", domain: "Reading: Informational Text", description: "Analyze in detail how a key individual, event, or idea is introduced, illustrated, and elaborated in a text." },
  { code: "CCSS.ELA-LITERACY.RI.7.1", grade: "7", domain: "Reading: Informational Text", description: "Cite several pieces of textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text." },
  { code: "CCSS.ELA-LITERACY.RI.7.2", grade: "7", domain: "Reading: Informational Text", description: "Determine two or more central ideas in a text and analyze their development over the course of the text; provide an objective summary of the text." },
  { code: "CCSS.ELA-LITERACY.RI.7.3", grade: "7", domain: "Reading: Informational Text", description: "Analyze the interactions between individuals, events, and ideas in a text." },
  { code: "CCSS.ELA-LITERACY.RI.8.1", grade: "8", domain: "Reading: Informational Text", description: "Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text." },
  { code: "CCSS.ELA-LITERACY.RI.8.2", grade: "8", domain: "Reading: Informational Text", description: "Determine a central idea of a text and analyze its development over the course of the text, including its relationship to supporting ideas." },
  { code: "CCSS.ELA-LITERACY.RI.8.3", grade: "8", domain: "Reading: Informational Text", description: "Analyze how a text makes connections among and distinctions between individuals, ideas, or events." },

  // ---- Writing (K-8) ----
  { code: "CCSS.ELA-LITERACY.W.K.1", grade: "K", domain: "Writing", description: "Use a combination of drawing, dictating, and writing to compose opinion pieces in which they tell a reader the topic or the name of the book they are writing about and state an opinion or preference about the topic or book." },
  { code: "CCSS.ELA-LITERACY.W.K.2", grade: "K", domain: "Writing", description: "Use a combination of drawing, dictating, and writing to compose informative/explanatory texts in which they name what they are writing about and supply some information about the topic." },
  { code: "CCSS.ELA-LITERACY.W.K.3", grade: "K", domain: "Writing", description: "Use a combination of drawing, dictating, and writing to narrate a single event or several loosely linked events, tell about the events in the order in which they occurred, and provide a reaction to what happened." },
  { code: "CCSS.ELA-LITERACY.W.1.1", grade: "1", domain: "Writing", description: "Write opinion pieces in which they introduce the topic or name the book they are writing about, state an opinion, supply a reason for the opinion, and provide some sense of closure." },
  { code: "CCSS.ELA-LITERACY.W.1.2", grade: "1", domain: "Writing", description: "Write informative/explanatory texts in which they name a topic, supply some facts about the topic, and provide some sense of closure." },
  { code: "CCSS.ELA-LITERACY.W.1.3", grade: "1", domain: "Writing", description: "Write narratives in which they recount two or more appropriately sequenced events, include some details, and provide some sense of closure." },
  { code: "CCSS.ELA-LITERACY.W.2.1", grade: "2", domain: "Writing", description: "Write opinion pieces in which they introduce the topic or book they are writing about, state an opinion, supply reasons that support the opinion, and provide a concluding statement or section." },
  { code: "CCSS.ELA-LITERACY.W.2.2", grade: "2", domain: "Writing", description: "Write informative/explanatory texts in which they introduce a topic, use facts and definitions to develop points, and provide a concluding statement or section." },
  { code: "CCSS.ELA-LITERACY.W.2.3", grade: "2", domain: "Writing", description: "Write narratives in which they recount a well-elaborated event or short sequence of events, include details, and provide a sense of closure." },
  { code: "CCSS.ELA-LITERACY.W.3.1", grade: "3", domain: "Writing", description: "Write opinion pieces on topics or texts, supporting a point of view with reasons." },
  { code: "CCSS.ELA-LITERACY.W.3.2", grade: "3", domain: "Writing", description: "Write informative/explanatory texts to examine a topic and convey ideas and information clearly." },
  { code: "CCSS.ELA-LITERACY.W.3.3", grade: "3", domain: "Writing", description: "Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences." },
  { code: "CCSS.ELA-LITERACY.W.4.1", grade: "4", domain: "Writing", description: "Write opinion pieces on topics or texts, supporting a point of view with reasons and information." },
  { code: "CCSS.ELA-LITERACY.W.4.2", grade: "4", domain: "Writing", description: "Write informative/explanatory texts to examine a topic and convey ideas and information clearly." },
  { code: "CCSS.ELA-LITERACY.W.4.3", grade: "4", domain: "Writing", description: "Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences." },
  { code: "CCSS.ELA-LITERACY.W.5.1", grade: "5", domain: "Writing", description: "Write opinion pieces on topics or texts, supporting a point of view with reasons and information." },
  { code: "CCSS.ELA-LITERACY.W.5.2", grade: "5", domain: "Writing", description: "Write informative/explanatory texts to examine a topic and convey ideas and information clearly." },
  { code: "CCSS.ELA-LITERACY.W.5.3", grade: "5", domain: "Writing", description: "Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences." },
  { code: "CCSS.ELA-LITERACY.W.6.1", grade: "6", domain: "Writing", description: "Write arguments to support claims with clear reasons and relevant evidence." },
  { code: "CCSS.ELA-LITERACY.W.6.2", grade: "6", domain: "Writing", description: "Write informative/explanatory texts to examine a topic and convey ideas, concepts, and information through the selection, organization, and analysis of relevant content." },
  { code: "CCSS.ELA-LITERACY.W.6.3", grade: "6", domain: "Writing", description: "Write narratives to develop real or imagined experiences or events using effective technique, relevant descriptive details, and well-structured event sequences." },
  { code: "CCSS.ELA-LITERACY.W.7.1", grade: "7", domain: "Writing", description: "Write arguments to support claims with clear reasons and relevant evidence." },
  { code: "CCSS.ELA-LITERACY.W.7.2", grade: "7", domain: "Writing", description: "Write informative/explanatory texts to examine a topic and convey ideas, concepts, and information through the selection, organization, and analysis of relevant content." },
  { code: "CCSS.ELA-LITERACY.W.7.3", grade: "7", domain: "Writing", description: "Write narratives to develop real or imagined experiences or events using effective technique, relevant descriptive details, and well-structured event sequences." },
  { code: "CCSS.ELA-LITERACY.W.8.1", grade: "8", domain: "Writing", description: "Write arguments to support claims with clear reasons and relevant evidence." },
  { code: "CCSS.ELA-LITERACY.W.8.2", grade: "8", domain: "Writing", description: "Write informative/explanatory texts to examine a topic and convey ideas, concepts, and information through the selection, organization, and analysis of relevant content." },
  { code: "CCSS.ELA-LITERACY.W.8.3", grade: "8", domain: "Writing", description: "Write narratives to develop real or imagined experiences or events using effective technique, relevant descriptive details, and well-structured event sequences." },

  // ---- Speaking & Listening (K-8) ----
  { code: "CCSS.ELA-LITERACY.SL.K.1", grade: "K", domain: "Speaking & Listening", description: "Participate in collaborative conversations with diverse partners about kindergarten topics and texts with peers and adults in small and larger groups." },
  { code: "CCSS.ELA-LITERACY.SL.K.2", grade: "K", domain: "Speaking & Listening", description: "Confirm understanding of a text read aloud or information presented orally or through other media by asking and answering questions about key details." },
  { code: "CCSS.ELA-LITERACY.SL.1.1", grade: "1", domain: "Speaking & Listening", description: "Participate in collaborative conversations with diverse partners about grade 1 topics and texts with peers and adults in small and larger groups." },
  { code: "CCSS.ELA-LITERACY.SL.1.2", grade: "1", domain: "Speaking & Listening", description: "Ask and answer questions about key details in a text read aloud or information presented orally or through other media." },
  { code: "CCSS.ELA-LITERACY.SL.2.1", grade: "2", domain: "Speaking & Listening", description: "Participate in collaborative conversations with diverse partners about grade 2 topics and texts with peers and adults in small and larger groups." },
  { code: "CCSS.ELA-LITERACY.SL.2.2", grade: "2", domain: "Speaking & Listening", description: "Recount or describe key ideas or details from a text read aloud or information presented orally or through other media." },
  { code: "CCSS.ELA-LITERACY.SL.3.1", grade: "3", domain: "Speaking & Listening", description: "Engage effectively in a range of collaborative discussions with diverse partners on grade 3 topics and texts, building on others' ideas and expressing their own clearly." },
  { code: "CCSS.ELA-LITERACY.SL.3.2", grade: "3", domain: "Speaking & Listening", description: "Determine the main ideas and supporting details of a text read aloud or information presented in diverse media and formats." },
  { code: "CCSS.ELA-LITERACY.SL.4.1", grade: "4", domain: "Speaking & Listening", description: "Engage effectively in a range of collaborative discussions with diverse partners on grade 4 topics and texts, building on others' ideas and expressing their own clearly." },
  { code: "CCSS.ELA-LITERACY.SL.4.2", grade: "4", domain: "Speaking & Listening", description: "Paraphrase portions of a text read aloud or information presented in diverse media and formats." },
  { code: "CCSS.ELA-LITERACY.SL.5.1", grade: "5", domain: "Speaking & Listening", description: "Engage effectively in a range of collaborative discussions with diverse partners on grade 5 topics and texts, building on others' ideas and expressing their own clearly." },
  { code: "CCSS.ELA-LITERACY.SL.5.2", grade: "5", domain: "Speaking & Listening", description: "Summarize a written text read aloud or information presented in diverse media and formats." },
  { code: "CCSS.ELA-LITERACY.SL.6.1", grade: "6", domain: "Speaking & Listening", description: "Engage effectively in a range of collaborative discussions with diverse partners on grade 6 topics, texts, and issues, building on others' ideas and expressing their own clearly." },
  { code: "CCSS.ELA-LITERACY.SL.6.2", grade: "6", domain: "Speaking & Listening", description: "Interpret information presented in diverse media and formats and explain how it contributes to a topic, text, or issue under study." },
  { code: "CCSS.ELA-LITERACY.SL.7.1", grade: "7", domain: "Speaking & Listening", description: "Engage effectively in a range of collaborative discussions with diverse partners on grade 7 topics, texts, and issues, building on others' ideas and expressing their own clearly." },
  { code: "CCSS.ELA-LITERACY.SL.7.4", grade: "7", domain: "Speaking & Listening", description: "Present claims and findings, emphasizing salient points in a focused, coherent manner with pertinent descriptions, facts, details, and examples." },
  { code: "CCSS.ELA-LITERACY.SL.8.1", grade: "8", domain: "Speaking & Listening", description: "Engage effectively in a range of collaborative discussions with diverse partners on grade 8 topics, texts, and issues, building on others' ideas and expressing their own clearly." },
  { code: "CCSS.ELA-LITERACY.SL.8.4", grade: "8", domain: "Speaking & Listening", description: "Present claims and findings, emphasizing salient points in a focused, coherent manner with relevant evidence, sound valid reasoning, and well-chosen details." },

  // ---- Language (K-8) ----
  { code: "CCSS.ELA-LITERACY.L.K.1", grade: "K", domain: "Language", description: "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking." },
  { code: "CCSS.ELA-LITERACY.L.K.2", grade: "K", domain: "Language", description: "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing." },
  { code: "CCSS.ELA-LITERACY.L.1.1", grade: "1", domain: "Language", description: "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking." },
  { code: "CCSS.ELA-LITERACY.L.1.2", grade: "1", domain: "Language", description: "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing." },
  { code: "CCSS.ELA-LITERACY.L.2.1", grade: "2", domain: "Language", description: "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking." },
  { code: "CCSS.ELA-LITERACY.L.2.2", grade: "2", domain: "Language", description: "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing." },
  { code: "CCSS.ELA-LITERACY.L.3.1", grade: "3", domain: "Language", description: "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking." },
  { code: "CCSS.ELA-LITERACY.L.3.2", grade: "3", domain: "Language", description: "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing." },
  { code: "CCSS.ELA-LITERACY.L.3.3", grade: "3", domain: "Language", description: "Use knowledge of language and its conventions when writing, speaking, reading, or listening." },
  { code: "CCSS.ELA-LITERACY.L.4.1", grade: "4", domain: "Language", description: "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking." },
  { code: "CCSS.ELA-LITERACY.L.4.2", grade: "4", domain: "Language", description: "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing." },
  { code: "CCSS.ELA-LITERACY.L.4.4", grade: "4", domain: "Language", description: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 4 reading and content." },
  { code: "CCSS.ELA-LITERACY.L.5.1", grade: "5", domain: "Language", description: "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking." },
  { code: "CCSS.ELA-LITERACY.L.5.2", grade: "5", domain: "Language", description: "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing." },
  { code: "CCSS.ELA-LITERACY.L.5.4", grade: "5", domain: "Language", description: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 5 reading and content." },
  { code: "CCSS.ELA-LITERACY.L.6.1", grade: "6", domain: "Language", description: "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking." },
  { code: "CCSS.ELA-LITERACY.L.6.2", grade: "6", domain: "Language", description: "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing." },
  { code: "CCSS.ELA-LITERACY.L.6.4", grade: "6", domain: "Language", description: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 6 reading and content." },
  { code: "CCSS.ELA-LITERACY.L.6.6", grade: "6", domain: "Language", description: "Acquire and use accurately grade-appropriate general academic and domain-specific words and phrases." },
  { code: "CCSS.ELA-LITERACY.L.7.1", grade: "7", domain: "Language", description: "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking." },
  { code: "CCSS.ELA-LITERACY.L.7.2", grade: "7", domain: "Language", description: "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing." },
  { code: "CCSS.ELA-LITERACY.L.7.4", grade: "7", domain: "Language", description: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 7 reading and content." },
  { code: "CCSS.ELA-LITERACY.L.8.1", grade: "8", domain: "Language", description: "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking." },
  { code: "CCSS.ELA-LITERACY.L.8.2", grade: "8", domain: "Language", description: "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing." },
  { code: "CCSS.ELA-LITERACY.L.8.4", grade: "8", domain: "Language", description: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 8 reading and content." },
];
