// Small starter word sets for the Thesaurus/Dictionary tools.
// Teacher-facing content library growth is a V2 concern; this keeps the
// tools functional for early-elementary vocabulary out of the box.
export const THESAURUS: Record<string, string[]> = {
  happy: ['glad', 'joyful', 'cheerful', 'pleased'],
  sad: ['unhappy', 'blue', 'down', 'gloomy'],
  big: ['large', 'huge', 'giant', 'great'],
  small: ['little', 'tiny', 'mini', 'petite'],
  fast: ['quick', 'speedy', 'rapid', 'swift'],
  slow: ['unhurried', 'sluggish', 'gradual'],
  good: ['great', 'nice', 'fine', 'wonderful'],
  bad: ['poor', 'terrible', 'awful', 'not good'],
  smart: ['clever', 'bright', 'wise', 'sharp'],
  funny: ['silly', 'hilarious', 'amusing', 'goofy'],
  scared: ['afraid', 'frightened', 'nervous', 'worried'],
  loud: ['noisy', 'booming', 'thunderous'],
  quiet: ['silent', 'hushed', 'soft', 'calm'],
  pretty: ['beautiful', 'lovely', 'pretty', 'cute'],
  strong: ['powerful', 'tough', 'mighty'],
  tired: ['sleepy', 'exhausted', 'worn out'],
  hard: ['difficult', 'tough', 'tricky'],
  easy: ['simple', 'effortless', 'a piece of cake'],
  begin: ['start', 'commence', 'kick off'],
  end: ['finish', 'stop', 'conclude'],
};

export const DICTIONARY: Record<string, string> = {
  brave: 'Ready to face danger or pain without being overly afraid.',
  curious: 'Eager to learn or know something.',
  friend: 'A person you like and enjoy spending time with.',
  gentle: 'Kind and careful; not rough.',
  habitat: 'The natural home of an animal or plant.',
  imagine: 'To form a picture or idea in your mind.',
  journey: 'A trip from one place to another.',
  kind: 'Friendly, caring, and helpful toward others.',
  library: 'A place with books you can read or borrow.',
  magnet: 'An object that pulls certain metals toward it.',
  neighbor: 'A person who lives near you.',
  observe: 'To watch something carefully.',
  patient: 'Able to wait calmly without getting upset.',
  question: 'Something you ask to learn an answer.',
  respect: 'To treat someone or something with care and consideration.',
  sentence: 'A group of words that expresses a complete thought.',
  team: 'A group of people working together.',
  unique: 'Being the only one of its kind; special.',
  vowel: 'A letter like a, e, i, o, or u.',
  wonder: 'To feel curious or amazed about something.',
};

export const SOUND_WALL: { symbol: string; example: string }[] = [
  { symbol: 'a', example: 'apple' },
  { symbol: 'b', example: 'ball' },
  { symbol: 'c', example: 'cat' },
  { symbol: 'ch', example: 'chip' },
  { symbol: 'd', example: 'dog' },
  { symbol: 'e', example: 'egg' },
  { symbol: 'f', example: 'fish' },
  { symbol: 'g', example: 'goat' },
  { symbol: 'h', example: 'hat' },
  { symbol: 'i', example: 'igloo' },
  { symbol: 'j', example: 'jam' },
  { symbol: 'k', example: 'kite' },
  { symbol: 'l', example: 'lamp' },
  { symbol: 'm', example: 'moon' },
  { symbol: 'n', example: 'nest' },
  { symbol: 'o', example: 'octopus' },
  { symbol: 'p', example: 'pig' },
  { symbol: 'qu', example: 'queen' },
  { symbol: 'r', example: 'rain' },
  { symbol: 's', example: 'sun' },
  { symbol: 'sh', example: 'ship' },
  { symbol: 't', example: 'top' },
  { symbol: 'th', example: 'thumb' },
  { symbol: 'u', example: 'umbrella' },
  { symbol: 'v', example: 'van' },
  { symbol: 'w', example: 'web' },
  { symbol: 'x', example: 'box' },
  { symbol: 'y', example: 'yarn' },
  { symbol: 'z', example: 'zebra' },
];
